/* eslint-disable */
// THIS FILE IS GENERATED — do not edit by hand.
// Source: @brightlocal/ui-components@2.25.0 — the type checker's view of
// dist/index.d.ts (the REAL barrel), not component-meta.json. The meta file
// lists exports that do not exist in the published dist (H1/P/Muted →
// TypographyH1/…P/…Muted, InputPassword → InputPasswordRoot, etc.) — grounding
// the allowlist in the meta produced "Element type is invalid" preview crashes.
// Only COMPONENT-shaped exports are listed: type aliases (SidebarSide,
// SidebarVariant) are erased at runtime and were never emittable as JSX.
// Regenerate: pnpm -F @gradeui/studio generate:brightlocal-contracts

/** Every real component export of the published barrel — what the model may emit. */
export const BRIGHTLOCAL_ALLOWED_COMPONENTS = [
  "Accordion",
  "AccordionContent",
  "AccordionItem",
  "AccordionTrigger",
  "Alert",
  "AlertDescription",
  "AlertDestructive",
  "AlertDialog",
  "AlertDialogAction",
  "AlertDialogCancel",
  "AlertDialogContent",
  "AlertDialogDescription",
  "AlertDialogFooter",
  "AlertDialogHeader",
  "AlertDialogOverlay",
  "AlertDialogPortal",
  "AlertDialogTitle",
  "AlertDialogTrigger",
  "AlertInfo",
  "AlertSuccess",
  "AlertTitle",
  "AlertWarning",
  "Area",
  "AreaChart",
  "AspectRatio",
  "Avatar",
  "AvatarFallback",
  "AvatarImage",
  "Badge",
  "Bar",
  "BarChart",
  "BrandIllustrationMotif",
  "Breadcrumb",
  "BreadcrumbEllipsis",
  "BreadcrumbItem",
  "BreadcrumbLink",
  "BreadcrumbList",
  "BreadcrumbPage",
  "BreadcrumbSeparator",
  "Button",
  "Calendar",
  "CalendarDayButton",
  "Callout",
  "CalloutCitation",
  "CalloutHeading",
  "Card",
  "CardAction",
  "CardContent",
  "CardDescription",
  "CardFooter",
  "CardHeader",
  "CardMedia",
  "CardTitle",
  "Carousel",
  "CarouselContent",
  "CarouselDots",
  "CarouselItem",
  "CarouselNext",
  "CarouselPrevious",
  "CartesianGrid",
  "Cell",
  "CentredLayout",
  "CentredLayoutContent",
  "CentredLayoutHeader",
  "ChartCenterLabel",
  "ChartContainer",
  "ChartDot",
  "ChartDotOnStroke",
  "ChartLabel",
  "ChartLegend",
  "ChartLegendContent",
  "ChartPieLabelList",
  "ChartPieLabelWrapper",
  "ChartRadarGrid",
  "ChartRadarLabelWrapper",
  "ChartStyle",
  "ChartTooltip",
  "ChartTooltipContent",
  "ChartsLegend",
  "ChartsTooltip",
  "Checkbox",
  "Chip",
  "Collapsible",
  "CollapsibleContent",
  "CollapsibleTrigger",
  "Combobox",
  "ComboboxContent",
  "ComboboxEmpty",
  "ComboboxGroup",
  "ComboboxInput",
  "ComboboxItem",
  "ComboboxList",
  "ComboboxLoading",
  "ComboboxSeparator",
  "ComboboxTrigger",
  "ComboboxValue",
  "ComboboxVirtualList",
  "Command",
  "CommandEmpty",
  "CommandGroup",
  "CommandInput",
  "CommandItem",
  "CommandList",
  "CommandSeparator",
  "CommandShortcut",
  "CommandVirtualItem",
  "CommandVirtualList",
  "ContextMenu",
  "ContextMenuCheckboxItem",
  "ContextMenuContent",
  "ContextMenuGroup",
  "ContextMenuItem",
  "ContextMenuLabel",
  "ContextMenuPortal",
  "ContextMenuRadioGroup",
  "ContextMenuRadioItem",
  "ContextMenuSeparator",
  "ContextMenuShortcut",
  "ContextMenuSub",
  "ContextMenuSubContent",
  "ContextMenuSubTrigger",
  "ContextMenuTrigger",
  "Customized",
  "DataTable",
  "DataTableBulkActions",
  "DataTableBulkActionsActions",
  "DataTableBulkActionsSummary",
  "DataTableColumnHeader",
  "DataTablePagination",
  "DataTablePaginationNav",
  "DataTablePaginationRowCount",
  "DataTableSearch",
  "DataTableSelectAllCheckbox",
  "DataTableSelectRowCheckbox",
  "DataTableToolbar",
  "DataTableToolbarLeft",
  "DataTableToolbarRight",
  "DatePickerCalendar",
  "DatePickerContent",
  "DatePickerPresets",
  "DatePickerRoot",
  "DatePickerTrigger",
  "Description",
  "Dialog",
  "DialogClose",
  "DialogContent",
  "DialogDescription",
  "DialogFooter",
  "DialogHeader",
  "DialogOverlay",
  "DialogPortal",
  "DialogTitle",
  "DialogTrigger",
  "Drawer",
  "DrawerBody",
  "DrawerClose",
  "DrawerContent",
  "DrawerDescription",
  "DrawerFooter",
  "DrawerHeader",
  "DrawerOverlay",
  "DrawerPortal",
  "DrawerTitle",
  "DrawerTrigger",
  "DropdownMenu",
  "DropdownMenuCheckboxItem",
  "DropdownMenuContent",
  "DropdownMenuGroup",
  "DropdownMenuItem",
  "DropdownMenuLabel",
  "DropdownMenuPortal",
  "DropdownMenuRadioGroup",
  "DropdownMenuRadioItem",
  "DropdownMenuSeparator",
  "DropdownMenuShortcut",
  "DropdownMenuSub",
  "DropdownMenuSubContent",
  "DropdownMenuSubTrigger",
  "DropdownMenuTrigger",
  "DropdownMenuTriggerAvatar",
  "Field",
  "FieldContent",
  "FieldDescription",
  "FieldError",
  "FieldErrorIcon",
  "FieldGroup",
  "FieldLabel",
  "FieldLegend",
  "FieldSet",
  "GlobalLayout",
  "GlobalLayoutBackLink",
  "GlobalLayoutContent",
  "GlobalLayoutContentActions",
  "GlobalLayoutContentBody",
  "GlobalLayoutContentHeader",
  "GlobalLayoutMobileHeader",
  "GlobalLayoutSidebar",
  "GlobalLayoutSubtitle",
  "Header",
  "HeightTransition",
  "HoverCard",
  "HoverCardContent",
  "HoverCardTrigger",
  "Input",
  "InputChip",
  "InputChipInput",
  "InputChipItems",
  "InputGroup",
  "InputGroupAddon",
  "InputGroupButton",
  "InputGroupInput",
  "InputList",
  "InputListAddButton",
  "InputListInput",
  "InputListItems",
  "InputOTP",
  "InputOTPDigitsOnly",
  "InputOTPGroup",
  "InputOTPSeparator",
  "InputOTPSimple",
  "InputOTPSlot",
  "InputOTPWithSeparator",
  "InputOTPWithSpacing",
  "InputPasswordField",
  "InputPasswordRoot",
  "InputPasswordStrength",
  "InputPasswordToggle",
  "Item",
  "ItemActions",
  "ItemContent",
  "ItemDescription",
  "ItemMedia",
  "ItemSubheader",
  "ItemTitle",
  "Label",
  "LabelList",
  "Line",
  "LineChart",
  "Link",
  "List",
  "Loading",
  "Logo",
  "MapClusterPin",
  "MapControlButton",
  "MapErrorState",
  "MapGridPin",
  "MapLegend",
  "MapLegendItem",
  "MapLoadingState",
  "MapLocationPin",
  "MapPopover",
  "MapPopoverAnchor",
  "MapPopoverContent",
  "Menubar",
  "MenubarCheckboxItem",
  "MenubarContent",
  "MenubarItem",
  "MenubarLabel",
  "MenubarMenu",
  "MenubarRadioGroup",
  "MenubarRadioItem",
  "MenubarSeparator",
  "MenubarShortcut",
  "MenubarSub",
  "MenubarSubContent",
  "MenubarSubTrigger",
  "MenubarTrigger",
  "NavigationMenu",
  "NavigationMenuContent",
  "NavigationMenuIndicator",
  "NavigationMenuItem",
  "NavigationMenuLink",
  "NavigationMenuList",
  "NavigationMenuTrigger",
  "NavigationMenuViewport",
  "Pagination",
  "PaginationButton",
  "PaginationContent",
  "PaginationEllipsis",
  "PaginationItem",
  "PaginationLink",
  "PaginationNext",
  "PaginationPrevious",
  "Pie",
  "PieChart",
  "PolarAngleAxis",
  "PolarGrid",
  "PolarRadiusAxis",
  "Popover",
  "PopoverAnchor",
  "PopoverContent",
  "PopoverTrigger",
  "Progress",
  "Radar",
  "RadarChart",
  "RadialBar",
  "RadialBarChart",
  "RadioGroup",
  "RadioGroupItem",
  "Rating",
  "Rectangle",
  "ReducedMotionOverrideContext",
  "ReferenceLine",
  "ResizableHandle",
  "ResizablePanel",
  "ResizablePanelGroup",
  "ResponsiveContainer",
  "ScrollArea",
  "ScrollBar",
  "Sector",
  "Select",
  "SelectContent",
  "SelectGroup",
  "SelectItem",
  "SelectLabel",
  "SelectScrollDownButton",
  "SelectScrollUpButton",
  "SelectSeparator",
  "SelectTrigger",
  "SelectValue",
  "Separator",
  "SeparatorWithText",
  "Sheet",
  "SheetClose",
  "SheetContent",
  "SheetDescription",
  "SheetFooter",
  "SheetHeader",
  "SheetOverlay",
  "SheetPortal",
  "SheetTitle",
  "SheetTrigger",
  "Sidebar",
  "SidebarAccountDropdown",
  "SidebarCollapseIcon",
  "SidebarContent",
  "SidebarDrawer",
  "SidebarFooter",
  "SidebarGroup",
  "SidebarGroupAction",
  "SidebarGroupContent",
  "SidebarGroupLabel",
  "SidebarHeader",
  "SidebarHeaderButton",
  "SidebarInboxItem",
  "SidebarInput",
  "SidebarInset",
  "SidebarMenu",
  "SidebarMenuAction",
  "SidebarMenuBadge",
  "SidebarMenuButton",
  "SidebarMenuCollapsible",
  "SidebarMenuCollapsibleContent",
  "SidebarMenuCollapsibleTrigger",
  "SidebarMenuItem",
  "SidebarMenuSkeleton",
  "SidebarMenuSub",
  "SidebarMenuSubButton",
  "SidebarMenuSubItem",
  "SidebarPopoverMenu",
  "SidebarPopoverMenuItem",
  "SidebarPopoverTrigger",
  "SidebarProvider",
  "SidebarRail",
  "SidebarSeparator",
  "SidebarSwitcher",
  "SidebarTrigger",
  "Skeleton",
  "Slider",
  "Sonner",
  "SplitLayout",
  "SplitLayoutContentLeft",
  "SplitLayoutContentRight",
  "SplitLayoutHeader",
  "SplitLayoutImage",
  "Stepper",
  "StepperContent",
  "StepperDescription",
  "StepperIndicator",
  "StepperItem",
  "StepperNav",
  "StepperSeparator",
  "StepperTitle",
  "StepperTrigger",
  "Switch",
  "Table",
  "TableBody",
  "TableCaption",
  "TableCell",
  "TableFooter",
  "TableHead",
  "TableHeader",
  "TableRow",
  "Tabs",
  "TabsContent",
  "TabsList",
  "TabsTrigger",
  "TextRevealMotion",
  "Textarea",
  "Toggle",
  "ToggleGroup",
  "ToggleGroupItem",
  "Tooltip",
  "TooltipContent",
  "TooltipProvider",
  "TooltipTrigger",
  "TypographyBlockquote",
  "TypographyCode",
  "TypographyH1",
  "TypographyH2",
  "TypographyH3",
  "TypographyH4",
  "TypographyInlineCode",
  "TypographyLarge",
  "TypographyLead",
  "TypographyList",
  "TypographyMuted",
  "TypographyP",
  "TypographySmall",
  "VirtualizedDataTable",
  "XAxis",
  "YAxis"
] as const;

/** Export → per-file subpath (from each export's declaring module).
 * Consumed by exporters only (registry.package.importMap): Studio keeps
 * the barrel internally. */
export const BRIGHTLOCAL_IMPORT_MAP: Readonly<Record<string, string>> = Object.freeze({
  "Accordion": "@brightlocal/ui-components/accordion",
  "AccordionContent": "@brightlocal/ui-components/accordion",
  "AccordionItem": "@brightlocal/ui-components/accordion",
  "AccordionTrigger": "@brightlocal/ui-components/accordion",
  "Alert": "@brightlocal/ui-components/alert",
  "AlertDescription": "@brightlocal/ui-components/alert",
  "AlertDestructive": "@brightlocal/ui-components/alert",
  "AlertDialog": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogAction": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogCancel": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogContent": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogDescription": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogFooter": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogHeader": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogOverlay": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogPortal": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogTitle": "@brightlocal/ui-components/alert-dialog",
  "AlertDialogTrigger": "@brightlocal/ui-components/alert-dialog",
  "AlertInfo": "@brightlocal/ui-components/alert",
  "AlertSuccess": "@brightlocal/ui-components/alert",
  "AlertTitle": "@brightlocal/ui-components/alert",
  "AlertWarning": "@brightlocal/ui-components/alert",
  "AspectRatio": "@brightlocal/ui-components/aspect-ratio",
  "Avatar": "@brightlocal/ui-components/avatar",
  "AvatarFallback": "@brightlocal/ui-components/avatar",
  "AvatarImage": "@brightlocal/ui-components/avatar",
  "Badge": "@brightlocal/ui-components/badge",
  "BrandIllustrationMotif": "@brightlocal/ui-components/brand-illustration-motif",
  "Breadcrumb": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbEllipsis": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbItem": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbLink": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbList": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbPage": "@brightlocal/ui-components/breadcrumb",
  "BreadcrumbSeparator": "@brightlocal/ui-components/breadcrumb",
  "Button": "@brightlocal/ui-components/button",
  "Calendar": "@brightlocal/ui-components/calendar",
  "CalendarDayButton": "@brightlocal/ui-components/calendar",
  "Callout": "@brightlocal/ui-components/callout",
  "CalloutCitation": "@brightlocal/ui-components/callout",
  "CalloutHeading": "@brightlocal/ui-components/callout",
  "Card": "@brightlocal/ui-components/card",
  "CardAction": "@brightlocal/ui-components/card",
  "CardContent": "@brightlocal/ui-components/card",
  "CardDescription": "@brightlocal/ui-components/card",
  "CardFooter": "@brightlocal/ui-components/card",
  "CardHeader": "@brightlocal/ui-components/card",
  "CardMedia": "@brightlocal/ui-components/card",
  "CardTitle": "@brightlocal/ui-components/card",
  "Carousel": "@brightlocal/ui-components/carousel",
  "CarouselContent": "@brightlocal/ui-components/carousel",
  "CarouselDots": "@brightlocal/ui-components/carousel",
  "CarouselItem": "@brightlocal/ui-components/carousel",
  "CarouselNext": "@brightlocal/ui-components/carousel",
  "CarouselPrevious": "@brightlocal/ui-components/carousel",
  "CentredLayout": "@brightlocal/ui-components/centred-layout",
  "CentredLayoutContent": "@brightlocal/ui-components/centred-layout",
  "CentredLayoutHeader": "@brightlocal/ui-components/centred-layout",
  "ChartCenterLabel": "@brightlocal/ui-components/chart",
  "ChartContainer": "@brightlocal/ui-components/chart",
  "ChartDot": "@brightlocal/ui-components/chart",
  "ChartDotOnStroke": "@brightlocal/ui-components/chart",
  "ChartLegend": "@brightlocal/ui-components/chart",
  "ChartLegendContent": "@brightlocal/ui-components/chart",
  "ChartPieLabelList": "@brightlocal/ui-components/chart",
  "ChartPieLabelWrapper": "@brightlocal/ui-components/chart",
  "ChartRadarGrid": "@brightlocal/ui-components/chart",
  "ChartRadarLabelWrapper": "@brightlocal/ui-components/chart",
  "ChartStyle": "@brightlocal/ui-components/chart",
  "ChartTooltip": "@brightlocal/ui-components/chart",
  "ChartTooltipContent": "@brightlocal/ui-components/chart",
  "Checkbox": "@brightlocal/ui-components/checkbox",
  "Chip": "@brightlocal/ui-components/chip",
  "Collapsible": "@brightlocal/ui-components/collapsible",
  "CollapsibleContent": "@brightlocal/ui-components/collapsible",
  "CollapsibleTrigger": "@brightlocal/ui-components/collapsible",
  "Combobox": "@brightlocal/ui-components/combobox",
  "ComboboxContent": "@brightlocal/ui-components/combobox",
  "ComboboxEmpty": "@brightlocal/ui-components/combobox",
  "ComboboxGroup": "@brightlocal/ui-components/combobox",
  "ComboboxInput": "@brightlocal/ui-components/combobox",
  "ComboboxItem": "@brightlocal/ui-components/combobox",
  "ComboboxList": "@brightlocal/ui-components/combobox",
  "ComboboxLoading": "@brightlocal/ui-components/combobox",
  "ComboboxSeparator": "@brightlocal/ui-components/combobox",
  "ComboboxTrigger": "@brightlocal/ui-components/combobox",
  "ComboboxValue": "@brightlocal/ui-components/combobox",
  "ComboboxVirtualList": "@brightlocal/ui-components/combobox",
  "Command": "@brightlocal/ui-components/command",
  "CommandEmpty": "@brightlocal/ui-components/command",
  "CommandGroup": "@brightlocal/ui-components/command",
  "CommandInput": "@brightlocal/ui-components/command",
  "CommandItem": "@brightlocal/ui-components/command",
  "CommandList": "@brightlocal/ui-components/command",
  "CommandSeparator": "@brightlocal/ui-components/command",
  "CommandShortcut": "@brightlocal/ui-components/command",
  "CommandVirtualItem": "@brightlocal/ui-components/command",
  "CommandVirtualList": "@brightlocal/ui-components/command",
  "ContextMenu": "@brightlocal/ui-components/context-menu",
  "ContextMenuCheckboxItem": "@brightlocal/ui-components/context-menu",
  "ContextMenuContent": "@brightlocal/ui-components/context-menu",
  "ContextMenuGroup": "@brightlocal/ui-components/context-menu",
  "ContextMenuItem": "@brightlocal/ui-components/context-menu",
  "ContextMenuLabel": "@brightlocal/ui-components/context-menu",
  "ContextMenuPortal": "@brightlocal/ui-components/context-menu",
  "ContextMenuRadioGroup": "@brightlocal/ui-components/context-menu",
  "ContextMenuRadioItem": "@brightlocal/ui-components/context-menu",
  "ContextMenuSeparator": "@brightlocal/ui-components/context-menu",
  "ContextMenuShortcut": "@brightlocal/ui-components/context-menu",
  "ContextMenuSub": "@brightlocal/ui-components/context-menu",
  "ContextMenuSubContent": "@brightlocal/ui-components/context-menu",
  "ContextMenuSubTrigger": "@brightlocal/ui-components/context-menu",
  "ContextMenuTrigger": "@brightlocal/ui-components/context-menu",
  "DataTable": "@brightlocal/ui-components/data-table",
  "DataTableBulkActions": "@brightlocal/ui-components/data-table",
  "DataTableBulkActionsActions": "@brightlocal/ui-components/data-table",
  "DataTableBulkActionsSummary": "@brightlocal/ui-components/data-table",
  "DataTableColumnHeader": "@brightlocal/ui-components/data-table",
  "DataTablePagination": "@brightlocal/ui-components/data-table",
  "DataTablePaginationNav": "@brightlocal/ui-components/data-table",
  "DataTablePaginationRowCount": "@brightlocal/ui-components/data-table",
  "DataTableSearch": "@brightlocal/ui-components/data-table",
  "DataTableSelectAllCheckbox": "@brightlocal/ui-components/data-table",
  "DataTableSelectRowCheckbox": "@brightlocal/ui-components/data-table",
  "DataTableToolbar": "@brightlocal/ui-components/data-table",
  "DataTableToolbarLeft": "@brightlocal/ui-components/data-table",
  "DataTableToolbarRight": "@brightlocal/ui-components/data-table",
  "DatePickerCalendar": "@brightlocal/ui-components/date-picker",
  "DatePickerContent": "@brightlocal/ui-components/date-picker",
  "DatePickerPresets": "@brightlocal/ui-components/date-picker",
  "DatePickerRoot": "@brightlocal/ui-components/date-picker",
  "DatePickerTrigger": "@brightlocal/ui-components/date-picker",
  "Description": "@brightlocal/ui-components/description",
  "Dialog": "@brightlocal/ui-components/dialog",
  "DialogClose": "@brightlocal/ui-components/dialog",
  "DialogContent": "@brightlocal/ui-components/dialog",
  "DialogDescription": "@brightlocal/ui-components/dialog",
  "DialogFooter": "@brightlocal/ui-components/dialog",
  "DialogHeader": "@brightlocal/ui-components/dialog",
  "DialogOverlay": "@brightlocal/ui-components/dialog",
  "DialogPortal": "@brightlocal/ui-components/dialog",
  "DialogTitle": "@brightlocal/ui-components/dialog",
  "DialogTrigger": "@brightlocal/ui-components/dialog",
  "Drawer": "@brightlocal/ui-components/drawer",
  "DrawerBody": "@brightlocal/ui-components/drawer",
  "DrawerClose": "@brightlocal/ui-components/drawer",
  "DrawerContent": "@brightlocal/ui-components/drawer",
  "DrawerDescription": "@brightlocal/ui-components/drawer",
  "DrawerFooter": "@brightlocal/ui-components/drawer",
  "DrawerHeader": "@brightlocal/ui-components/drawer",
  "DrawerOverlay": "@brightlocal/ui-components/drawer",
  "DrawerPortal": "@brightlocal/ui-components/drawer",
  "DrawerTitle": "@brightlocal/ui-components/drawer",
  "DrawerTrigger": "@brightlocal/ui-components/drawer",
  "DropdownMenu": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuCheckboxItem": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuContent": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuGroup": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuItem": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuLabel": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuPortal": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuRadioGroup": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuRadioItem": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuSeparator": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuShortcut": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuSub": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuSubContent": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuSubTrigger": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuTrigger": "@brightlocal/ui-components/dropdown-menu",
  "DropdownMenuTriggerAvatar": "@brightlocal/ui-components/dropdown-menu",
  "Field": "@brightlocal/ui-components/field",
  "FieldContent": "@brightlocal/ui-components/field",
  "FieldDescription": "@brightlocal/ui-components/field",
  "FieldError": "@brightlocal/ui-components/field",
  "FieldErrorIcon": "@brightlocal/ui-components/field",
  "FieldGroup": "@brightlocal/ui-components/field",
  "FieldLabel": "@brightlocal/ui-components/field",
  "FieldLegend": "@brightlocal/ui-components/field",
  "FieldSet": "@brightlocal/ui-components/field",
  "GlobalLayout": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutBackLink": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutContent": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutContentActions": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutContentBody": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutContentHeader": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutMobileHeader": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutSidebar": "@brightlocal/ui-components/global-layout",
  "GlobalLayoutSubtitle": "@brightlocal/ui-components/global-layout",
  "Header": "@brightlocal/ui-components/header",
  "HeightTransition": "@brightlocal/ui-components/height-transition",
  "HoverCard": "@brightlocal/ui-components/hover-card",
  "HoverCardContent": "@brightlocal/ui-components/hover-card",
  "HoverCardTrigger": "@brightlocal/ui-components/hover-card",
  "Input": "@brightlocal/ui-components/input",
  "InputChip": "@brightlocal/ui-components/input-chip",
  "InputChipInput": "@brightlocal/ui-components/input-chip",
  "InputChipItems": "@brightlocal/ui-components/input-chip",
  "InputGroup": "@brightlocal/ui-components/input-group",
  "InputGroupAddon": "@brightlocal/ui-components/input-group",
  "InputGroupButton": "@brightlocal/ui-components/input-group",
  "InputGroupInput": "@brightlocal/ui-components/input-group",
  "InputList": "@brightlocal/ui-components/input-list",
  "InputListAddButton": "@brightlocal/ui-components/input-list",
  "InputListInput": "@brightlocal/ui-components/input-list",
  "InputListItems": "@brightlocal/ui-components/input-list",
  "InputOTP": "@brightlocal/ui-components/input-otp",
  "InputOTPDigitsOnly": "@brightlocal/ui-components/input-otp",
  "InputOTPGroup": "@brightlocal/ui-components/input-otp",
  "InputOTPSeparator": "@brightlocal/ui-components/input-otp",
  "InputOTPSimple": "@brightlocal/ui-components/input-otp",
  "InputOTPSlot": "@brightlocal/ui-components/input-otp",
  "InputOTPWithSeparator": "@brightlocal/ui-components/input-otp",
  "InputOTPWithSpacing": "@brightlocal/ui-components/input-otp",
  "InputPasswordField": "@brightlocal/ui-components/input-password",
  "InputPasswordRoot": "@brightlocal/ui-components/input-password",
  "InputPasswordStrength": "@brightlocal/ui-components/input-password",
  "InputPasswordToggle": "@brightlocal/ui-components/input-password",
  "Item": "@brightlocal/ui-components/list",
  "ItemActions": "@brightlocal/ui-components/list",
  "ItemContent": "@brightlocal/ui-components/list",
  "ItemDescription": "@brightlocal/ui-components/list",
  "ItemMedia": "@brightlocal/ui-components/list",
  "ItemSubheader": "@brightlocal/ui-components/list",
  "ItemTitle": "@brightlocal/ui-components/list",
  "Label": "@brightlocal/ui-components/label",
  "Link": "@brightlocal/ui-components/link",
  "List": "@brightlocal/ui-components/list",
  "Loading": "@brightlocal/ui-components/loading",
  "Logo": "@brightlocal/ui-components/logo",
  "MapClusterPin": "@brightlocal/ui-components/map",
  "MapControlButton": "@brightlocal/ui-components/map",
  "MapErrorState": "@brightlocal/ui-components/map",
  "MapGridPin": "@brightlocal/ui-components/map",
  "MapLegend": "@brightlocal/ui-components/map",
  "MapLegendItem": "@brightlocal/ui-components/map",
  "MapLoadingState": "@brightlocal/ui-components/map",
  "MapLocationPin": "@brightlocal/ui-components/map",
  "MapPopover": "@brightlocal/ui-components/map",
  "MapPopoverAnchor": "@brightlocal/ui-components/map",
  "MapPopoverContent": "@brightlocal/ui-components/map",
  "Menubar": "@brightlocal/ui-components/menubar",
  "MenubarCheckboxItem": "@brightlocal/ui-components/menubar",
  "MenubarContent": "@brightlocal/ui-components/menubar",
  "MenubarItem": "@brightlocal/ui-components/menubar",
  "MenubarLabel": "@brightlocal/ui-components/menubar",
  "MenubarMenu": "@brightlocal/ui-components/menubar",
  "MenubarRadioGroup": "@brightlocal/ui-components/menubar",
  "MenubarRadioItem": "@brightlocal/ui-components/menubar",
  "MenubarSeparator": "@brightlocal/ui-components/menubar",
  "MenubarShortcut": "@brightlocal/ui-components/menubar",
  "MenubarSub": "@brightlocal/ui-components/menubar",
  "MenubarSubContent": "@brightlocal/ui-components/menubar",
  "MenubarSubTrigger": "@brightlocal/ui-components/menubar",
  "MenubarTrigger": "@brightlocal/ui-components/menubar",
  "NavigationMenu": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuContent": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuIndicator": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuItem": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuLink": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuList": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuTrigger": "@brightlocal/ui-components/navigation-menu",
  "NavigationMenuViewport": "@brightlocal/ui-components/navigation-menu",
  "Pagination": "@brightlocal/ui-components/pagination",
  "PaginationButton": "@brightlocal/ui-components/pagination",
  "PaginationContent": "@brightlocal/ui-components/pagination",
  "PaginationEllipsis": "@brightlocal/ui-components/pagination",
  "PaginationItem": "@brightlocal/ui-components/pagination",
  "PaginationLink": "@brightlocal/ui-components/pagination",
  "PaginationNext": "@brightlocal/ui-components/pagination",
  "PaginationPrevious": "@brightlocal/ui-components/pagination",
  "Popover": "@brightlocal/ui-components/popover",
  "PopoverAnchor": "@brightlocal/ui-components/popover",
  "PopoverContent": "@brightlocal/ui-components/popover",
  "PopoverTrigger": "@brightlocal/ui-components/popover",
  "Progress": "@brightlocal/ui-components/progress",
  "RadioGroup": "@brightlocal/ui-components/radio-group",
  "RadioGroupItem": "@brightlocal/ui-components/radio-group",
  "Rating": "@brightlocal/ui-components/rating",
  "ReducedMotionOverrideContext": "@brightlocal/ui-components/hooks/use-prefers-reduced-motion",
  "ResizableHandle": "@brightlocal/ui-components/resizable",
  "ResizablePanel": "@brightlocal/ui-components/resizable",
  "ResizablePanelGroup": "@brightlocal/ui-components/resizable",
  "ScrollArea": "@brightlocal/ui-components/scroll-area",
  "ScrollBar": "@brightlocal/ui-components/scroll-area",
  "Select": "@brightlocal/ui-components/select",
  "SelectContent": "@brightlocal/ui-components/select",
  "SelectGroup": "@brightlocal/ui-components/select",
  "SelectItem": "@brightlocal/ui-components/select",
  "SelectLabel": "@brightlocal/ui-components/select",
  "SelectScrollDownButton": "@brightlocal/ui-components/select",
  "SelectScrollUpButton": "@brightlocal/ui-components/select",
  "SelectSeparator": "@brightlocal/ui-components/select",
  "SelectTrigger": "@brightlocal/ui-components/select",
  "SelectValue": "@brightlocal/ui-components/select",
  "Separator": "@brightlocal/ui-components/separator",
  "SeparatorWithText": "@brightlocal/ui-components/separator",
  "Sheet": "@brightlocal/ui-components/sheet",
  "SheetClose": "@brightlocal/ui-components/sheet",
  "SheetContent": "@brightlocal/ui-components/sheet",
  "SheetDescription": "@brightlocal/ui-components/sheet",
  "SheetFooter": "@brightlocal/ui-components/sheet",
  "SheetHeader": "@brightlocal/ui-components/sheet",
  "SheetOverlay": "@brightlocal/ui-components/sheet",
  "SheetPortal": "@brightlocal/ui-components/sheet",
  "SheetTitle": "@brightlocal/ui-components/sheet",
  "SheetTrigger": "@brightlocal/ui-components/sheet",
  "Sidebar": "@brightlocal/ui-components/sidebar",
  "SidebarAccountDropdown": "@brightlocal/ui-components/sidebar",
  "SidebarCollapseIcon": "@brightlocal/ui-components/sidebar",
  "SidebarContent": "@brightlocal/ui-components/sidebar",
  "SidebarDrawer": "@brightlocal/ui-components/sidebar",
  "SidebarFooter": "@brightlocal/ui-components/sidebar",
  "SidebarGroup": "@brightlocal/ui-components/sidebar",
  "SidebarGroupAction": "@brightlocal/ui-components/sidebar",
  "SidebarGroupContent": "@brightlocal/ui-components/sidebar",
  "SidebarGroupLabel": "@brightlocal/ui-components/sidebar",
  "SidebarHeader": "@brightlocal/ui-components/sidebar",
  "SidebarHeaderButton": "@brightlocal/ui-components/sidebar",
  "SidebarInboxItem": "@brightlocal/ui-components/sidebar",
  "SidebarInput": "@brightlocal/ui-components/sidebar",
  "SidebarInset": "@brightlocal/ui-components/sidebar",
  "SidebarMenu": "@brightlocal/ui-components/sidebar",
  "SidebarMenuAction": "@brightlocal/ui-components/sidebar",
  "SidebarMenuBadge": "@brightlocal/ui-components/sidebar",
  "SidebarMenuButton": "@brightlocal/ui-components/sidebar",
  "SidebarMenuCollapsible": "@brightlocal/ui-components/sidebar",
  "SidebarMenuCollapsibleContent": "@brightlocal/ui-components/sidebar",
  "SidebarMenuCollapsibleTrigger": "@brightlocal/ui-components/sidebar",
  "SidebarMenuItem": "@brightlocal/ui-components/sidebar",
  "SidebarMenuSkeleton": "@brightlocal/ui-components/sidebar",
  "SidebarMenuSub": "@brightlocal/ui-components/sidebar",
  "SidebarMenuSubButton": "@brightlocal/ui-components/sidebar",
  "SidebarMenuSubItem": "@brightlocal/ui-components/sidebar",
  "SidebarPopoverMenu": "@brightlocal/ui-components/sidebar",
  "SidebarPopoverMenuItem": "@brightlocal/ui-components/sidebar",
  "SidebarPopoverTrigger": "@brightlocal/ui-components/sidebar",
  "SidebarProvider": "@brightlocal/ui-components/sidebar",
  "SidebarRail": "@brightlocal/ui-components/sidebar",
  "SidebarSeparator": "@brightlocal/ui-components/sidebar",
  "SidebarSwitcher": "@brightlocal/ui-components/sidebar",
  "SidebarTrigger": "@brightlocal/ui-components/sidebar",
  "Skeleton": "@brightlocal/ui-components/skeleton",
  "Slider": "@brightlocal/ui-components/slider",
  "Sonner": "@brightlocal/ui-components/sonner",
  "SplitLayout": "@brightlocal/ui-components/split-layout",
  "SplitLayoutContentLeft": "@brightlocal/ui-components/split-layout",
  "SplitLayoutContentRight": "@brightlocal/ui-components/split-layout",
  "SplitLayoutHeader": "@brightlocal/ui-components/split-layout",
  "SplitLayoutImage": "@brightlocal/ui-components/split-layout",
  "Stepper": "@brightlocal/ui-components/stepper",
  "StepperContent": "@brightlocal/ui-components/stepper",
  "StepperDescription": "@brightlocal/ui-components/stepper",
  "StepperIndicator": "@brightlocal/ui-components/stepper",
  "StepperItem": "@brightlocal/ui-components/stepper",
  "StepperNav": "@brightlocal/ui-components/stepper",
  "StepperSeparator": "@brightlocal/ui-components/stepper",
  "StepperTitle": "@brightlocal/ui-components/stepper",
  "StepperTrigger": "@brightlocal/ui-components/stepper",
  "Switch": "@brightlocal/ui-components/switch",
  "Table": "@brightlocal/ui-components/table",
  "TableBody": "@brightlocal/ui-components/table",
  "TableCaption": "@brightlocal/ui-components/table",
  "TableCell": "@brightlocal/ui-components/table",
  "TableFooter": "@brightlocal/ui-components/table",
  "TableHead": "@brightlocal/ui-components/table",
  "TableHeader": "@brightlocal/ui-components/table",
  "TableRow": "@brightlocal/ui-components/table",
  "Tabs": "@brightlocal/ui-components/tabs",
  "TabsContent": "@brightlocal/ui-components/tabs",
  "TabsList": "@brightlocal/ui-components/tabs",
  "TabsTrigger": "@brightlocal/ui-components/tabs",
  "TextRevealMotion": "@brightlocal/ui-components/text-reveal-motion",
  "Textarea": "@brightlocal/ui-components/textarea",
  "Toggle": "@brightlocal/ui-components/toggle",
  "ToggleGroup": "@brightlocal/ui-components/toggle-group",
  "ToggleGroupItem": "@brightlocal/ui-components/toggle-group",
  "Tooltip": "@brightlocal/ui-components/tooltip",
  "TooltipContent": "@brightlocal/ui-components/tooltip",
  "TooltipProvider": "@brightlocal/ui-components/tooltip",
  "TooltipTrigger": "@brightlocal/ui-components/tooltip",
  "TypographyBlockquote": "@brightlocal/ui-components/typography",
  "TypographyCode": "@brightlocal/ui-components/typography",
  "TypographyH1": "@brightlocal/ui-components/typography",
  "TypographyH2": "@brightlocal/ui-components/typography",
  "TypographyH3": "@brightlocal/ui-components/typography",
  "TypographyH4": "@brightlocal/ui-components/typography",
  "TypographyInlineCode": "@brightlocal/ui-components/typography",
  "TypographyLarge": "@brightlocal/ui-components/typography",
  "TypographyLead": "@brightlocal/ui-components/typography",
  "TypographyList": "@brightlocal/ui-components/typography",
  "TypographyMuted": "@brightlocal/ui-components/typography",
  "TypographyP": "@brightlocal/ui-components/typography",
  "TypographySmall": "@brightlocal/ui-components/typography",
  "VirtualizedDataTable": "@brightlocal/ui-components/data-table",
  "cn": "@brightlocal/ui-components/lib/utils",
});
