// AUTO-GENERATED by scripts/generate-brightlocal-contracts.mjs from
// registries/brightlocal/sidecars/*.md — do not hand-edit; re-run the
// script after a sidecar review pass. Serialisable contract specs (no
// zod — registry rule 1); the settings panel converts these into real
// ComponentContracts at the edge (apps/docs/lib/registry-contracts).
import type { RegistryContractSpec } from "../types";

export const BRIGHTLOCAL_CONTRACTS: Readonly<
  Record<string, RegistryContractSpec>
> = {
  "Accordion": {
    "name": "Accordion",
    "description": "Vertically stacked collapsible sections with mutual-exclusion support.",
    "props": {
      "type": {
        "kind": "enum",
        "values": [
          "single",
          "multiple"
        ],
        "design": "plumbing",
        "optional": true
      },
      "collapsible": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "AlertDialog": {
    "name": "AlertDialog",
    "description": "Modal dialog for confirming destructive or irreversible actions.",
    "props": {
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Alert": {
    "name": "Alert",
    "description": "Informational banner for success, warning, error, or info messages.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "success",
          "info",
          "destructive",
          "warning"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "title": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "description": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "action": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default"
    }
  },
  "AspectRatio": {
    "name": "AspectRatio",
    "description": "Wrapper that enforces a fixed aspect ratio on its child element.",
    "props": {
      "ratio": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Avatar": {
    "name": "Avatar",
    "description": "Circular image with fallback initials for user profile pictures.",
    "props": {
      "src": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "alt": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Badge": {
    "name": "Badge",
    "description": "Small status label with semantic color variants (default, secondary, destructive, outline).",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "secondary",
          "destructive",
          "outline"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "asChild": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default"
    }
  },
  "Breadcrumb": {
    "name": "Breadcrumb",
    "description": "Navigation trail showing the current page location in a hierarchy.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Button": {
    "name": "Button",
    "description": "Interactive button with variants (default, destructive, outline, secondary, ghost, warning), sizes, loading state, and iconOnly mode.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "destructive",
          "outline",
          "secondary",
          "ghost",
          "warning"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "size": {
        "kind": "enum",
        "values": [
          "default",
          "sm",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "loading": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "fullWidth": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "iconOnly": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "asChild": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "type": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "ariaLabel": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default",
      "size": "default"
    }
  },
  "Calendar": {
    "name": "Calendar",
    "description": "Date picker calendar grid for selecting single dates or date ranges.",
    "props": {
      "numberOfMonths": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "mode": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "selected": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onSelect": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Callout": {
    "name": "Callout",
    "description": "Speech bubble callout for highlighting key statements, quotes, or important messages. Features a directional pointer/caret and bold heading typography.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "primary",
          "purple",
          "blue",
          "green"
        ],
        "design": "knob",
        "optional": true,
        "default": "primary"
      },
      "pointer": {
        "kind": "enum",
        "values": [
          "top",
          "bottom",
          "left",
          "right",
          "none"
        ],
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "primary"
    }
  },
  "Card": {
    "name": "Card",
    "description": "Contained surface with header, content, and footer sections. Full-width by default — constrain via className.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "filled",
          "transparent",
          "border",
          "transparent-flush"
        ],
        "design": "knob",
        "optional": true,
        "default": "filled"
      },
      "density": {
        "kind": "enum",
        "values": [
          "default",
          "condensed"
        ],
        "design": "knob",
        "optional": true
      },
      "align": {
        "kind": "enum",
        "values": [
          "left",
          "center",
          "right"
        ],
        "design": "knob",
        "optional": true
      },
      "maxWidth": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "filled"
    }
  },
  "Carousel": {
    "name": "Carousel",
    "description": "Horizontal scrollable content viewer with navigation controls.",
    "props": {
      "orientation": {
        "kind": "enum",
        "values": [
          "horizontal",
          "vertical"
        ],
        "design": "knob",
        "optional": true
      },
      "opts": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "plugins": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "setApi": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "lazyLoad": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "overscan": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "CentredLayout": {
    "name": "CentredLayout",
    "description": "Page layout centered horizontally with max-width constraint.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "ChartContainer": {
    "name": "ChartContainer",
    "description": "Recharts wrapper with design system theming for bar, line, area, pie, and radar charts.",
    "props": {
      "config": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "id": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Checkbox": {
    "name": "Checkbox",
    "description": "Toggle control for boolean values with checked, unchecked, and indeterminate states.",
    "props": {
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "checked": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onCheckedChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Chip": {
    "name": "Chip",
    "description": "Removable tag/chip element for multi-value inputs and filters.",
    "props": {
      "size": {
        "kind": "enum",
        "values": [
          "md",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "md"
      },
      "loading": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onRemove": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "maxWidth": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "size": "md"
    }
  },
  "Collapsible": {
    "name": "Collapsible",
    "description": "Unstyled Radix primitive for toggling content visibility.",
    "props": {
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "defaultOpen": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Combobox": {
    "name": "Combobox",
    "description": "Searchable, filterable dropdown for selecting from large option lists. Supports single and multi-select.",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "shouldFilter": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "side": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "sideOffset": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "avoidCollisions": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Command": {
    "name": "Command",
    "description": "Keyboard-driven command palette for search and actions.",
    "props": {
      "filter": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "onClear": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "debounceMs": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "ContextMenu": {
    "name": "ContextMenu",
    "description": "Right-click menu with nested submenus.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "DataTable": {
    "name": "DataTable",
    "description": "Full-featured data table with sorting, filtering, pagination, and row selection.",
    "props": {
      "columns": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "data": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "enableSorting": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "enableGlobalFiltering": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "enableRowSelection": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "enablePagination": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "pageSize": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "isLoading": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "noResultsMessage": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "DatePickerRoot": {
    "name": "DatePickerRoot",
    "description": "Date input with calendar dropdown for selecting dates.",
    "props": {
      "mode": {
        "kind": "enum",
        "values": [
          "single",
          "range"
        ],
        "design": "knob",
        "optional": true
      },
      "date": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onDateChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dateRange": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onDateRangeChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dateFormat": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Description": {
    "name": "Description",
    "description": "Key-value pair layout for displaying metadata.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Dialog": {
    "name": "Dialog",
    "description": "Modal overlay for focused content or forms with focus trapping.",
    "props": {
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "modal": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Drawer": {
    "name": "Drawer",
    "description": "Slide-in panel from screen edge with drag-to-dismiss gesture.",
    "props": {
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "direction": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "DropdownMenu": {
    "name": "DropdownMenu",
    "description": "Trigger-activated menu with items, submenus, checkboxes, and radio groups.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Field": {
    "name": "Field",
    "description": "Form field wrapper that connects label, input, description, and error message.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "box"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "orientation": {
        "kind": "enum",
        "values": [
          "vertical",
          "horizontal",
          "responsive"
        ],
        "design": "knob",
        "optional": true
      },
      "align": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default"
    }
  },
  "GlobalLayout": {
    "name": "GlobalLayout",
    "description": "Root application layout with sidebar and main content area.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "full",
          "md",
          "sm"
        ],
        "design": "knob",
        "optional": true,
        "default": "full"
      },
      "maxWidth": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "width": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "full"
    }
  },
  "Header": {
    "name": "Header",
    "description": "Page or section header component.",
    "props": {
      "align": {
        "kind": "enum",
        "values": [
          "left",
          "center",
          "right"
        ],
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "HoverCard": {
    "name": "HoverCard",
    "description": "Popover that appears on hover for previewing linked content.",
    "props": {
      "openDelay": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "closeDelay": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "InputChip": {
    "name": "InputChip",
    "description": "Tag/chip input for entering multiple values as removable chips.",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "defaultValue": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "allowDuplicates": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "InputGroup": {
    "name": "InputGroup",
    "description": "Wrapper for grouping an input with prefix/suffix addons.",
    "props": {
      "size": {
        "kind": "enum",
        "values": [
          "default",
          "sm",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "size": "default"
    }
  },
  "InputList": {
    "name": "InputList",
    "description": "Managed list of text items with add-input, per-row remove controls, multi-line paste, max item limit, loading skeletons, and validation states.",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "children": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "className": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "InputOTP": {
    "name": "InputOTP",
    "description": "One-time password input with individual character cells.",
    "props": {
      "maxLength": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "pattern": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "InputPasswordRoot": {
    "name": "InputPasswordRoot",
    "description": "Password input with show/hide toggle.",
    "props": {
      "strengthLevels": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onStrengthChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "showMeter": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Input": {
    "name": "Input",
    "description": "Text input with error state and data-hook support.",
    "props": {
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "hasIcon": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "hasSecondaryIcon": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Label": {
    "name": "Label",
    "description": "Form label element that associates with inputs via htmlFor.",
    "props": {
      "optional": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "htmlFor": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Link": {
    "name": "Link",
    "description": "Styled anchor element for navigation with design system theming.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "inline",
          "filled",
          "outline",
          "ghost"
        ],
        "design": "knob",
        "optional": true,
        "default": "inline"
      },
      "external": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "showExternalIcon": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "asChild": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "inline"
    }
  },
  "List": {
    "name": "List",
    "description": "Vertical list container with Item sub-components (ItemMedia, ItemContent, ItemTitle, ItemDescription, ItemActions) for rendering structured rows.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "filled",
          "outline",
          "loading"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default"
    }
  },
  "Logo": {
    "name": "Logo",
    "description": "BrightLocal logo component with size variants.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "logotype",
          "mark"
        ],
        "design": "knob",
        "optional": true,
        "default": "logotype"
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "logotype"
    }
  },
  "MAP_STYLES": {
    "name": "MAP_STYLES",
    "description": "Vendor-agnostic map UI primitives: pins, tooltips, controls, legend, loading/error states.",
    "props": {
      "MapStyleVariant": {
        "kind": "enum",
        "values": [
          "default",
          "muted"
        ],
        "design": "knob",
        "optional": true
      },
      "MapGridPinVariant": {
        "kind": "enum",
        "values": [
          "strong",
          "moderate",
          "weak",
          "unranked",
          "error"
        ],
        "design": "knob",
        "optional": true
      },
      "variant": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "loading": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "animateIn": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "icon": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "iconOnly": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onRetry": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "retryLoading": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Menubar": {
    "name": "Menubar",
    "description": "Horizontal menu bar with dropdown submenus for application menus.",
    "props": {
      "defaultValue": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "NavigationMenu": {
    "name": "NavigationMenu",
    "description": "Horizontal navigation with dropdown panels for site navigation.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Pagination": {
    "name": "Pagination",
    "description": "Page navigation controls with previous/next and page number links.",
    "props": {
      "page": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "totalPages": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "siblingCount": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "boundaryCount": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Popover": {
    "name": "Popover",
    "description": "Floating panel anchored to a trigger for forms or interactive content.",
    "props": {
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "defaultOpen": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "modal": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "align": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "side": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "sideOffset": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Progress": {
    "name": "Progress",
    "description": "Horizontal progress bar with animated fill (0-100).",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "ariaLabel": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "label": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "indicatorClassName": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "RadioGroup": {
    "name": "RadioGroup",
    "description": "Group of mutually exclusive radio button options.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "box",
          "boxIconVertical",
          "boxIconHorizontal"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default"
    }
  },
  "Rating": {
    "name": "Rating",
    "description": "Star rating display and input component.",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "ResizablePanelGroup": {
    "name": "ResizablePanelGroup",
    "description": "Draggable split pane layout with resizable panels.",
    "props": {
      "direction": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "withHandle": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "defaultSize": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "minSize": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "maxSize": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "ScrollArea": {
    "name": "ScrollArea",
    "description": "Custom-styled scrollable container with overlay scrollbars.",
    "props": {
      "orientation": {
        "kind": "enum",
        "values": [
          "vertical",
          "horizontal"
        ],
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Select": {
    "name": "Select",
    "description": "Styled dropdown select with trigger, content, and item sub-components. Uses Radix (not native select).",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Separator": {
    "name": "Separator",
    "description": "Horizontal or vertical divider line.",
    "props": {
      "orientation": {
        "kind": "enum",
        "values": [
          "horizontal",
          "vertical"
        ],
        "design": "knob",
        "optional": true
      },
      "spacing": {
        "kind": "enum",
        "values": [
          "default",
          "sm",
          "md",
          "lg"
        ],
        "design": "knob",
        "optional": true
      },
      "decorative": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Sheet": {
    "name": "Sheet",
    "description": "Modal slide-in panel from screen edge (always modal, renders via portal).",
    "props": {
      "side": {
        "kind": "enum",
        "values": [
          "top",
          "right",
          "bottom",
          "left"
        ],
        "design": "knob",
        "optional": true
      },
      "open": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onOpenChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Sidebar": {
    "name": "Sidebar",
    "description": "Application sidebar layout with navigation menus, collapsible groups, and mobile support.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "sidebar"
        ],
        "design": "knob",
        "optional": true,
        "default": "sidebar"
      },
      "side": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "collapsible": {
        "kind": "enum",
        "values": [
          "offcanvas",
          "icon",
          "none"
        ],
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      },
      "embedded": {
        "kind": "string",
        "design": "plumbing",
        "description": "DEPRECATED since 2.9.0: Sidebar now always uses inline layout ()"
      }
    },
    "variantDefaults": {
      "variant": "sidebar"
    }
  },
  "Skeleton": {
    "name": "Skeleton",
    "description": "Placeholder shimmer animation for loading states.",
    "props": {
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "Slider": {
    "name": "Slider",
    "description": "Range input slider with single or dual thumbs.",
    "props": {
      "mode": {
        "kind": "enum",
        "values": [
          "single",
          "range"
        ],
        "design": "knob",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "defaultValue": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "min": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "max": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "step": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "thumbLabels": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Sonner": {
    "name": "Sonner",
    "description": "Toast notification system with auto-dismiss and action support.",
    "props": {
      "title": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "description": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "icon": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "colorSchema": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "button": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "duration": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "SplitLayout": {
    "name": "SplitLayout",
    "description": "Two-column layout with resizable split pane.",
    "props": {
      "left": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "right": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Stepper": {
    "name": "Stepper",
    "description": "Guides users through a multi-step process, showing progress and the current step.",
    "props": {
      "orientation": {
        "kind": "enum",
        "values": [
          "horizontal",
          "vertical"
        ],
        "design": "knob",
        "optional": true
      },
      "labelPlacement": {
        "kind": "enum",
        "values": [
          "below",
          "inline"
        ],
        "design": "knob",
        "optional": true
      },
      "state": {
        "kind": "enum",
        "values": [
          "active",
          "completed",
          "inactive",
          "error"
        ],
        "design": "knob",
        "optional": true
      },
      "steps": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "defaultValue": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "stepId": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "completed": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "loading": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Switch": {
    "name": "Switch",
    "description": "Toggle switch for on/off boolean values.",
    "props": {
      "disabled": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "checked": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "onCheckedChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Table": {
    "name": "Table",
    "description": "Styled HTML table with header, body, footer, and cell size variants.",
    "props": {
      "size": {
        "kind": "enum",
        "values": [
          "default",
          "md",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "align": {
        "kind": "enum",
        "values": [
          "left",
          "right",
          "center"
        ],
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "size": "default"
    }
  },
  "Tabs": {
    "name": "Tabs",
    "description": "Tabbed interface for switching between content panels.",
    "props": {
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "defaultValue": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "lazyMount": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "unmountOnExit": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "TextRevealMotion": {
    "name": "TextRevealMotion",
    "description": "Animated text reveal with a rolling shape-morphing ball.",
    "props": {
      "holdTime": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "shimmer": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "gradientFrom": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "gradientTo": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "Textarea": {
    "name": "Textarea",
    "description": "Multi-line text input with auto-resize support.",
    "props": {
      "error": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  },
  "ToggleGroup": {
    "name": "ToggleGroup",
    "description": "Group of toggle buttons with single or multi-select mode.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "outline"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "size": {
        "kind": "enum",
        "values": [
          "default",
          "sm",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "type": {
        "kind": "enum",
        "values": [
          "single",
          "multiple"
        ],
        "design": "plumbing",
        "optional": true
      },
      "value": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onValueChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default",
      "size": "default"
    }
  },
  "Toggle": {
    "name": "Toggle",
    "description": "Two-state button that can be pressed or unpressed.",
    "props": {
      "variant": {
        "kind": "enum",
        "values": [
          "default",
          "outline"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "size": {
        "kind": "enum",
        "values": [
          "default",
          "sm",
          "lg"
        ],
        "design": "knob",
        "optional": true,
        "default": "default"
      },
      "pressed": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "onPressedChange": {
        "kind": "string",
        "design": "event",
        "optional": true
      },
      "ariaLabel": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    },
    "variantDefaults": {
      "variant": "default",
      "size": "default"
    }
  },
  "Tooltip": {
    "name": "Tooltip",
    "description": "Small text popup that appears on hover/focus for supplementary info.",
    "props": {
      "delayDuration": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "skipDelayDuration": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "side": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "align": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "sideOffset": {
        "kind": "string",
        "design": "plumbing",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "optional": true,
        "description": "optional on structural components (renders data-hook)"
      }
    }
  },
  "TypographyH1": {
    "name": "TypographyH1",
    "description": "Styled typographic elements: headings (H1-H4), paragraph, blockquote, list, code, lead, and muted text.",
    "props": {
      "asChild": {
        "kind": "boolean",
        "design": "knob",
        "optional": true
      },
      "dataHook": {
        "kind": "string",
        "design": "plumbing",
        "description": "REQUIRED (renders data-hook; kebab-case {context}-{componentType}, e.g. \"settings-save-button\")"
      }
    }
  }
} as const;
