"use client";

/**
 * StarterPicker — the "+ New screen" doorway that isn't a blank slate.
 *
 * Two entry paths today; room for more:
 *
 *   1. "Start from a layout" — pick one of the hand-authored
 *      ReferenceLayouts shipped in `@gradeui/studio/playbook`. A thumbnail
 *      grid shows each; clicking creates a new design pre-seeded with
 *      the scaffold's JSX. Thumbnails are PNGs in
 *      `apps/docs/public/layout-thumbs/<id>.png`, generated by the
 *      Playwright script `scripts/capture-layout-thumbnails.mjs`.
 *      Missing PNG → CSS gradient fallback keyed off the layout id, so
 *      the dialog never looks broken mid-asset-regeneration.
 *
 *   2. "Paste your code" — drop in arbitrary JSX (e.g. from a codepen
 *      or a teammate) and spawn a new design from it. No validation
 *      beyond "not empty" — Sandpack will complain in-frame if the
 *      source doesn't run, same as any LLM-emitted code.
 *
 * "Blank" isn't in here — that's the existing "+ New screen" button on
 * the canvas toolbar. The picker is the starters path, not the
 * one-click-blank path.
 *
 * Why a single dialog instead of two buttons: the layouts and paste
 * flows will eventually share a "which DS theme is this using" chip
 * and a sidecar-authoring field. Single dialog, two tabs, grows
 * cleanly.
 *
 * Related tasks:
 *   - #45 layout picker + thumbnail capture (this file)
 *   - #46 paste-your-code entry (this file)
 *   - #25 retrieval pass — once that lands, "From prompt" becomes a
 *         third tab that auto-selects the best matching layout.
 */

import { useState } from "react";
import { FileText, LayoutGrid, Sparkles } from "lucide-react";
import {
  REFERENCE_LAYOUTS,
  type ReferenceLayout,
} from "@gradeui/studio/playbook";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  Button,
  Textarea,
} from "@gradeui/ui";
import { cn } from "@/lib/utils";

/**
 * Rewrite every `id: "..."` (or `'...'`) literal in a scaffold's JSX
 * to a fresh ID so two starter instantiations don't share entry keys.
 *
 * The pattern we target: `{ id: "alb-mm", title: "Midnight Memories",
 * ... }` inside a data array. Each occurrence gets replaced with a
 * fresh short ID. Other `id` usages (HTML `id=` attributes, CSS
 * selectors) aren't matched because they don't have the `id: "..."`
 * shape inside an object literal — JSX uses `id="..."` (no colon).
 *
 * IDs are short and human-readable (8 chars from a low-collision
 * alphabet, prefixed `gid-`). Not cryptographic — just unique enough
 * within a design. Cross-design collisions would require both
 * designs to roll the exact same suffix; ~36^8 = ~3 trillion, fine.
 */
function freshenScaffoldIds(source: string): string {
  return source.replace(
    /(\bid:\s*)(["'])([^"']+)(["'])/g,
    (_match, prefix: string, openQ: string, _oldId: string, closeQ: string) =>
      `${prefix}${openQ}${makeId()}${closeQ}`,
  );
}

function makeId(): string {
  const ALPHA = "abcdefghijklmnopqrstuvwxyz0123456789";
  let out = "gid-";
  for (let i = 0; i < 8; i++) {
    out += ALPHA[Math.floor(Math.random() * ALPHA.length)];
  }
  return out;
}

interface StarterPickerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** Called when the user picks a layout or submits pasted code. The
   *  parent spawns a new design with these values and focuses it. */
  onPick: (payload: {
    source: string;
    name?: string;
    /** Which starter path the source came from. Parent can log this
     *  later for discovery-metric purposes; ignored for now. */
    origin: "layout" | "paste";
    /** Non-null for layout starters — `ReferenceLayout["id"]`. */
    layoutId?: string;
  }) => void;
}

type Tab = "layouts" | "paste";

export function StarterPicker({
  open,
  onOpenChange,
  onPick,
}: StarterPickerProps) {
  const [tab, setTab] = useState<Tab>("layouts");

  const handlePickLayout = (layout: ReferenceLayout) => {
    onPick({
      // Rewrite every `id: "..."` literal in the scaffold to a fresh
      // UUID so two starter instantiations don't share keys. Without
      // this, opening Music App twice would yield identical entry IDs
      // ("alb-mm", "alb-cu", ...) which means the data-array mutator
      // can't tell the two designs' cards apart at edit time — and
      // any cross-design state keyed by entry id would collide.
      // Pasted JSX (below) goes through the same transform: model-
      // generated screens that already use the `{ id, ... }` pattern
      // get fresh IDs too.
      source: freshenScaffoldIds(layout.scaffold),
      name: layout.label,
      origin: "layout",
      layoutId: layout.id,
    });
    onOpenChange(false);
  };

  const handleSubmitPaste = (source: string) => {
    const trimmed = source.trim();
    if (!trimmed) return;
    onPick({
      source: freshenScaffoldIds(trimmed),
      origin: "paste",
    });
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      {/* Wider than the default Dialog max-w-lg — the layouts grid
          wants room to show three thumbnails per row without
          squashing. */}
      <DialogContent className="max-w-3xl p-0 gap-0 overflow-hidden">
        <DialogHeader className="px-6 pt-6 pb-3 border-b border-border">
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-primary" aria-hidden />
            Start a new screen
          </DialogTitle>
          <DialogDescription>
            Pick a reference layout to riff on, or paste JSX you already
            have. The new screen opens alongside your current ones — it
            doesn&apos;t clobber anything.
          </DialogDescription>
        </DialogHeader>

        {/* Tabs strip. Low-chrome segmented control rather than the
            Tabs component — this dialog is small enough that one level
            of segmentation is plenty. */}
        <div
          className="flex items-center gap-1 px-6 pt-3 border-b border-border"
          role="tablist"
          aria-label="Starter type"
        >
          <TabButton
            active={tab === "layouts"}
            onClick={() => setTab("layouts")}
            icon={<LayoutGrid className="h-3.5 w-3.5" />}
            label="Start from a layout"
          />
          <TabButton
            active={tab === "paste"}
            onClick={() => setTab("paste")}
            icon={<FileText className="h-3.5 w-3.5" />}
            label="Paste your code"
          />
        </div>

        {tab === "layouts" ? (
          <LayoutsGrid onPick={handlePickLayout} />
        ) : (
          <PasteCodeForm onSubmit={handleSubmitPaste} />
        )}
      </DialogContent>
    </Dialog>
  );
}

// ────────────────────────────────────────────────────────────────────
// Tab strip
// ────────────────────────────────────────────────────────────────────

function TabButton({
  active,
  onClick,
  icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
}) {
  return (
    <button
      type="button"
      role="tab"
      aria-selected={active}
      onClick={onClick}
      className={cn(
        "flex items-center gap-1.5 px-3 py-2 text-xs font-medium rounded-t-md",
        "border-b-2 -mb-px transition-colors",
        active
          ? "border-primary text-foreground"
          : "border-transparent text-muted-foreground hover:text-foreground"
      )}
    >
      {icon}
      {label}
    </button>
  );
}

// ────────────────────────────────────────────────────────────────────
// Layouts grid
// ────────────────────────────────────────────────────────────────────

function LayoutsGrid({ onPick }: { onPick: (l: ReferenceLayout) => void }) {
  return (
    <div className="px-6 py-5 max-h-[60vh] overflow-y-auto">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {REFERENCE_LAYOUTS.map((layout) => (
          <LayoutCard key={layout.id} layout={layout} onPick={() => onPick(layout)} />
        ))}
      </div>
    </div>
  );
}

function LayoutCard({
  layout,
  onPick,
}: {
  layout: ReferenceLayout;
  onPick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onPick}
      className={cn(
        "group flex flex-col rounded-lg border border-border bg-card",
        "overflow-hidden text-left",
        "hover:border-primary/60 hover:shadow-sm transition-all",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50"
      )}
    >
      <LayoutThumbnail id={layout.id} />
      <div className="flex-1 px-3 py-2.5 border-t border-border">
        <div className="text-xs font-medium text-foreground group-hover:text-primary transition-colors">
          {layout.label}
        </div>
        <p className="text-[11px] text-muted-foreground line-clamp-2 mt-0.5">
          {layout.description}
        </p>
      </div>
    </button>
  );
}

/**
 * Layout thumbnail. Tries `/layout-thumbs/<id>.png` first — that's the
 * canonical output of `scripts/capture-layout-thumbnails.mjs`. If the
 * PNG is missing (first-run before thumbnails are captured, or mid-
 * regenerate) we fall back to a deterministic gradient derived from
 * the id so the card still looks intentional rather than broken.
 *
 * The wrapper holds a 16:10 aspect ratio — matches the virtual
 * viewport we capture at (1280×800), so the preview isn't distorted.
 */
function LayoutThumbnail({ id }: { id: string }) {
  const [errored, setErrored] = useState(false);
  const src = `/layout-thumbs/${id}.png`;
  return (
    <div
      className="relative aspect-[16/10] w-full bg-muted overflow-hidden"
      style={
        errored
          ? {
              // Hash the id into two CSS variables so each layout gets
              // a distinct but on-theme gradient. Cheap, visually
              // distinct without branding-feeling.
              background: fallbackGradient(id),
            }
          : undefined
      }
    >
      {!errored && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt=""
          className="absolute inset-0 h-full w-full object-cover"
          onError={() => setErrored(true)}
          loading="lazy"
        />
      )}
      {errored && (
        <div className="absolute inset-0 flex items-center justify-center text-[10px] uppercase tracking-wide text-foreground/70 font-medium">
          {id}
        </div>
      )}
    </div>
  );
}

/**
 * Deterministic pastel gradient from a string. Seeds a tiny FNV-1a
 * hash into a pair of semantic-token-ish CSS vars so the fallback
 * thumbnail reads as "on-theme placeholder" rather than noise. Not
 * pretty; not meant to be — the real thumbnails replace this.
 */
function fallbackGradient(seed: string): string {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h = (h ^ seed.charCodeAt(i)) >>> 0;
    h = Math.imul(h, 16777619) >>> 0;
  }
  const a = h % 360;
  const b = (a + 60) % 360;
  return (
    `linear-gradient(135deg, ` +
    `hsl(${a} 55% 70% / 0.75) 0%, ` +
    `hsl(${b} 55% 80% / 0.5) 100%)`
  );
}

// ────────────────────────────────────────────────────────────────────
// Paste code form (#46)
// ────────────────────────────────────────────────────────────────────

function PasteCodeForm({ onSubmit }: { onSubmit: (source: string) => void }) {
  const [source, setSource] = useState("");
  const trimmed = source.trim();
  const canSubmit = trimmed.length > 0;

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        if (canSubmit) onSubmit(source);
      }}
      className="px-6 py-5 flex flex-col gap-3"
    >
      <label className="text-xs text-muted-foreground" htmlFor="paste-jsx">
        Drop JSX that exports a default <code>App</code> component. Uses the
        same Sandpack harness as the chat-generated code, so only{" "}
        <code>@gradeui/ui</code> and <code>lucide-react</code> imports
        resolve.
      </label>
      <Textarea
        id="paste-jsx"
        value={source}
        onChange={(e) => setSource(e.target.value)}
        placeholder={'import { Button, Card } from "@gradeui/ui";\n\nexport default function App() {\n  return (\n    <Card>…</Card>\n  );\n}\n'}
        className="font-mono text-xs min-h-[260px] max-h-[50vh]"
        spellCheck={false}
      />
      <div className="flex justify-end gap-2">
        <Button type="submit" disabled={!canSubmit} size="sm">
          Create screen
        </Button>
      </div>
    </form>
  );
}
