// Hub Page — Location hub: proposal shell + hub header + a responsive grid of HubStatCards linking into each module.
//
// FIRST SCREEN of the @brightlocal/proposal era (STUDIO-FLOWS M0): the
// shell, sidenav, page header and hub cards live in the shared registry
// module — packages/studio/registries/brightlocal/lib/proposal.jsx —
// and this template is JUST THE PAGE. Editing proposal.jsx (nav IA,
// card anatomy, shell presets) updates every screen that imports it;
// screens still carrying in-file copies stay as they are and migrate
// on regen. Data rides the ProposalDataProvider seam: the defaults ARE
// the demo data, so this screen mounts nothing — wrap in
// <ProposalDataProvider data={{...}}> to re-skin account/user/location/
// metrics in one move ("switch the data and it would be magic").
// Hand-authored — safe from harvest re-runs. Edit freely; re-run
// `node scripts/generate-registry-templates.mjs`.

import {
  SidebarProvider,
  SidebarTrigger,
  GlobalLayoutContentBody,
  Logo,
} from "@brightlocal/ui-components";
import {
  Globe,
  Grid3x3,
  Link,
  Menu,
  Star,
  Store,
  TrendingUp,
} from "@brightlocal/icons";
import {
  AppLayoutShell,
  ProposalSidebar,
  PageHeader,
  HubStatCard,
  HubHeroCard,
  ProposalDataProvider,
} from "@brightlocal/proposal";

// ─── Project data — the per-project wiring layer ─────────────────────
// navLinks map nav row ids → screen names (STUDIO-FLOWS): flows live in
// DATA, stable per project, editable without touching the IA. Providers
// STACK, so the tweaker's dataset switch keeps these links. Add area
// data (tables, insights) here as screens need it.
const PROJECT_DATA = {
  navLinks: {
    "rankings-table": "Rankings Table",
    // Keyword rows are generated by buildProposalSections with stable
    // index ids — link them all into the Local Search Grid screen.
    // Unresolvable targets no-op (a project without that screen loses
    // nothing).
    "local-search-grid-keyword-0": "Local Search Grid",
    "local-search-grid-keyword-1": "Local Search Grid",
    "local-search-grid-keyword-2": "Local Search Grid",
    "local-search-grid-keyword-3": "Local Search Grid",
    "local-search-grid-keyword-4": "Local Search Grid",
  },
};

export default function App() {
  return (
    <ProposalDataProvider data={PROJECT_DATA}>
    <SidebarProvider dataHook="switcher-sidebar-provider" defaultOpen>
      {/* Layout knobs are LITERAL props so the inspector can edit them —
          select the shell (click the page background) and flip
          flush / stickyHeader / pinnedSidebar / sidebarTone. */}
      <AppLayoutShell
        flush={true}
        stickyHeader={true}
        pinnedSidebar={true}
        sidebarTone="white"
        // activeId states WHICH PAGE THIS IS: the hub is the location's
        // landing, matching no nav row — nothing highlights, trails stay
        // collapsed. A module screen passes its row id instead
        // (activeId="rankings-table" on the Rankings Table screen).
        sidebar={<ProposalSidebar dataHook="app-sidebar" activeId="location-hub" />}
        header={
          // meta omitted ON PURPOSE — PageHeader's default meta is
          // data-bound (location name + status from useProposalData,
          // read at render position so dataset switches reach it).
          <PageHeader
            breadcrumbs={[{ label: "Your Locations", href: "#" }]}
            title="Location Hub"
            dataHook="page-header"
          />
        }
        mobileBar={
          <header className="flex items-center gap-1 px-1 py-1 lg:hidden">
            <SidebarTrigger dataHook="mobile-sidebar-trigger" className="size-11">
              <Menu className="size-5" />
            </SidebarTrigger>
            <Logo className="h-6" dataHook="mobile-logo" />
          </header>
        }
        dataHook="app-layout"
      >
        <GlobalLayoutContentBody dataHook="page-body">
          <HubHeroCard
            title="Get more from your local presence"
            description="AI Insights reviews your listings, rankings and reviews together and tells you the three things to fix first."
            primaryCta="Run AI Insights"
            primaryHook="hub-hero-primary"
            secondaryCta="See how it works"
            secondaryHook="hub-hero-secondary"
            dataHook="hub-hero-card"
          />
          {/* Tracks own the sizing — Card bakes max-w-[400px], hence
              max-w-none inside HubStatCard. metricKey = full data
              binding: metric/delta/description come from
              data.metrics.<key> at render position, so dataset
              switches (tweaker Data row, ProposalDataProvider) re-skin
              every card live. */}
          <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            <HubStatCard
              icon={Star}
              title="Reviews"
              metricKey="reviews"
              ctaHook="hub-reviews-cta"
              dataHook="hub-reviews-card"
            />
            <HubStatCard
              icon={TrendingUp}
              title="Rankings"
              metricKey="rankings"
              goto="Rankings Table"
              ctaHook="hub-rankings-cta"
              dataHook="hub-rankings-card"
            />
            <HubStatCard
              icon={Link}
              title="Citations"
              metricKey="citations"
              ctaHook="hub-citations-cta"
              dataHook="hub-citations-card"
            />
            <HubStatCard
              icon={Grid3x3}
              title="Local Search Grid"
              metricKey="localSearchGrid"
              goto="Local Search Grid"
              ctaHook="hub-local-search-grid-cta"
              dataHook="hub-local-search-grid-card"
            />
            <HubStatCard
              icon={Store}
              title="GBP Manager"
              metricKey="gbpManager"
              ctaHook="hub-gbp-cta"
              dataHook="hub-gbp-card"
            />
            <HubStatCard
              icon={Globe}
              title="Website SEO"
              metricKey="websiteSeo"
              ctaHook="hub-seo-cta"
              dataHook="hub-seo-card"
            />
          </div>
        </GlobalLayoutContentBody>
      </AppLayoutShell>
    </SidebarProvider>
    </ProposalDataProvider>
  );
}
