// GENERATED by scripts/publish-videos.mjs. Do not edit.
// The recorded facts about each video: how long it is, where its sections
// start and end, and every subtitle cue with its timing. The editorial parts
// (title, description, tags, order) live in lib/videos.ts and are keyed by
// slug, so re-publishing a recording never overwrites the writing.

export interface RecordedChapter {
  /** Stable, and also the thumbnail's filename: <flow>--<nn>-<card>. */
  id: string;
  card: string;
  title: string;
  description: string;
  t: number;
  end: number;
  thumb: string;
}

export interface RecordedCue { t: number; end: number; text: string }

export interface RecordedVideo {
  slug: string;
  duration: number;
  chapters: RecordedChapter[];
  transcript: RecordedCue[];
  /** One scrub-preview tile's size on the sprite sheet. */
  tileW: number;
  tileH: number;
}

export const RECORDED: RecordedVideo[] = [
  {
    "slug": "the-gap",
    "duration": 64.96,
    "chapters": [
      {
        "id": "the-gap--01-persona-multi",
        "card": "persona-multi",
        "title": "A multi-location brand",
        "description": "Customers compare Hove with Brighton, and their reviews say so.",
        "t": 0,
        "end": 19.63,
        "thumb": "/videos/thumbs/the-gap--01-persona-multi.jpg"
      },
      {
        "id": "the-gap--02-manager",
        "card": "manager",
        "title": "Review Manager",
        "description": "Every review in one inbox, and the plan for the ones waiting.",
        "t": 19.63,
        "end": 32.56,
        "thumb": "/videos/thumbs/the-gap--02-manager.jpg"
      },
      {
        "id": "the-gap--03-tracker",
        "card": "tracker",
        "title": "Review Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 32.56,
        "end": 49.11,
        "thumb": "/videos/thumbs/the-gap--03-tracker.jpg"
      },
      {
        "id": "the-gap--04-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 49.11,
        "end": 64.96,
        "thumb": "/videos/thumbs/the-gap--04-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.8129999999999997,
        "end": 6.038,
        "text": "Hove looks fine. The lifetime rating is 4.4."
      },
      {
        "t": 6.038,
        "end": 14.645,
        "text": "But the lifetime number cannot move. The last thirty days can."
      },
      {
        "t": 14.645,
        "end": 19.631,
        "text": "Two of the last ten reviews name Brighton as the standard."
      },
      {
        "t": 22.036,
        "end": 32.565,
        "text": "So the plan is about one branch, not the brand."
      },
      {
        "t": 34.973,
        "end": 49.114,
        "text": "The recent window is the number to watch."
      }
    ],
    "tileW": 240,
    "tileH": 136
  }
];
