// GENERATED by scripts/publish-videos.mjs. Do not edit.
// The recorded facts about each video: how long it is, where its sections
// start and end, and every subtitle cue with its timing. The editorial parts
// (title, description, tags, order) live in lib/videos.ts and are keyed by
// slug, so re-publishing a recording never overwrites the writing.

export interface RecordedChapter {
  /** Stable, and also the thumbnail's filename: <flow>--<nn>-<card>. */
  id: string;
  card: string;
  title: string;
  description: string;
  t: number;
  end: number;
  thumb: string;
}

export interface RecordedCue { t: number; end: number; text: string }

export interface RecordedVideo {
  slug: string;
  duration: number;
  chapters: RecordedChapter[];
  transcript: RecordedCue[];
  /** One scrub-preview tile's size on the sprite sheet. */
  tileW: number;
  tileH: number;
}

export const RECORDED: RecordedVideo[] = [
  {
    "slug": "day-one-to-habit",
    "duration": 61.97,
    "chapters": [
      {
        "id": "day-one-to-habit--01-persona-empty",
        "card": "persona-empty",
        "title": "Signed up, looking around",
        "description": "Nothing connected, nothing in. What does the product say to someone with no reviews?",
        "t": 0,
        "end": 14.62,
        "thumb": "/videos/thumbs/day-one-to-habit--01-persona-empty.jpg"
      },
      {
        "id": "day-one-to-habit--02-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 14.62,
        "end": 35.1,
        "thumb": "/videos/thumbs/day-one-to-habit--02-persona-starter.jpg"
      },
      {
        "id": "day-one-to-habit--03-persona-engaged",
        "card": "persona-engaged",
        "title": "A single location, engaged",
        "description": "Campaigns running, replies flowing, and a rating that is hard to move.",
        "t": 35.1,
        "end": 50.68,
        "thumb": "/videos/thumbs/day-one-to-habit--03-persona-engaged.jpg"
      },
      {
        "id": "day-one-to-habit--04-roadmap",
        "card": "roadmap",
        "title": "Insights & Actions",
        "description": "The next three months, one stage at a time.",
        "t": 50.68,
        "end": 58.14,
        "thumb": "/videos/thumbs/day-one-to-habit--04-roadmap.jpg"
      },
      {
        "id": "day-one-to-habit--05-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 58.14,
        "end": 61.97,
        "thumb": "/videos/thumbs/day-one-to-habit--05-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.641,
        "end": 6.07,
        "text": "No reviews, no sites connected, nothing to summarise."
      },
      {
        "t": 6.07,
        "end": 11.402,
        "text": "So it says why it matters, with a number you can cite."
      },
      {
        "t": 11.402,
        "end": 14.621,
        "text": "And one thing to do today: a code for the till."
      },
      {
        "t": 20.019,
        "end": 25.243,
        "text": "A week in. Four reviews, and a chart that will not lie about them."
      },
      {
        "t": 25.243,
        "end": 35.101,
        "text": "Too few for a trend, so it lists them instead."
      },
      {
        "t": 40.543,
        "end": 50.682,
        "text": "Eight months in, and now the six months mean something."
      },
      {
        "t": 53.089,
        "end": 58.138,
        "text": "Make reviews a habit, not a project."
      }
    ],
    "tileW": 320,
    "tileH": 180
  },
  {
    "slug": "insights-overview",
    "duration": 100.22999999999999,
    "chapters": [
      {
        "id": "insights-overview--01-beacon",
        "card": "beacon",
        "title": "Contextual Insights & Actions",
        "description": "Like someone sat next to you, telling you what to do about your reviews.",
        "t": 0,
        "end": 2.66,
        "thumb": "/videos/thumbs/insights-overview--01-beacon.jpg"
      },
      {
        "id": "insights-overview--02-persona-empty",
        "card": "persona-empty",
        "title": "Signed up, looking around",
        "description": "Nothing connected, nothing in. What does the product say to someone with no reviews?",
        "t": 2.66,
        "end": 14.61,
        "thumb": "/videos/thumbs/insights-overview--02-persona-empty.jpg"
      },
      {
        "id": "insights-overview--03-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 14.61,
        "end": 45.44,
        "thumb": "/videos/thumbs/insights-overview--03-persona-starter.jpg"
      },
      {
        "id": "insights-overview--04-persona-engaged",
        "card": "persona-engaged",
        "title": "A single location, engaged",
        "description": "Campaigns running, replies flowing, and a rating that is hard to move.",
        "t": 45.44,
        "end": 65.33,
        "thumb": "/videos/thumbs/insights-overview--04-persona-engaged.jpg"
      },
      {
        "id": "insights-overview--05-persona-multi",
        "card": "persona-multi",
        "title": "A multi-location brand",
        "description": "Customers compare Hove with Brighton, and their reviews say so.",
        "t": 65.33,
        "end": 83.83,
        "thumb": "/videos/thumbs/insights-overview--05-persona-multi.jpg"
      },
      {
        "id": "insights-overview--06-persona-lapsed",
        "card": "persona-lapsed",
        "title": "The trial ended",
        "description": "Reviews still arriving, nobody watching. How do we bring them back?",
        "t": 83.83,
        "end": 96.36,
        "thumb": "/videos/thumbs/insights-overview--06-persona-lapsed.jpg"
      },
      {
        "id": "insights-overview--07-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 96.36,
        "end": 100.22999999999999,
        "thumb": "/videos/thumbs/insights-overview--07-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 8.064,
        "end": 14.613,
        "text": "Day one. Nothing connected, nothing in."
      },
      {
        "t": 20.042,
        "end": 24.093,
        "text": "Three days left on the trial."
      },
      {
        "t": 24.093,
        "end": 30.707,
        "text": "What the trial has found so far."
      },
      {
        "t": 30.707,
        "end": 39.092,
        "text": "The plan for the week."
      },
      {
        "t": 39.092,
        "end": 45.442,
        "text": "And what auto-reply would have written, on one of their own reviews."
      },
      {
        "t": 50.85,
        "end": 65.325,
        "text": "Eight months in. What moved, and why."
      },
      {
        "t": 70.742,
        "end": 83.827,
        "text": "Customers compare Hove with Brighton, and their reviews say so."
      },
      {
        "t": 89.253,
        "end": 96.365,
        "text": "Nine days after the trial ended."
      }
    ],
    "tileW": 320,
    "tileH": 180
  },
  {
    "slug": "insights-popovers",
    "duration": 93.87,
    "chapters": [
      {
        "id": "insights-popovers--01-popovers",
        "card": "popovers",
        "title": "Insights with additional data",
        "description": "The eight dialogs, in order, with nothing else in the way.",
        "t": 0,
        "end": 2.61,
        "thumb": "/videos/thumbs/insights-popovers--01-popovers.jpg"
      },
      {
        "id": "insights-popovers--02-summary",
        "card": "summary",
        "title": "The summary",
        "description": "One headline, one line, and the findings you can open.",
        "t": 2.61,
        "end": 20.13,
        "thumb": "/videos/thumbs/insights-popovers--02-summary.jpg"
      },
      {
        "id": "insights-popovers--03-plan",
        "card": "plan",
        "title": "The plan",
        "description": "This week's goal, and what auto-reply would have written.",
        "t": 20.13,
        "end": 30.92,
        "thumb": "/videos/thumbs/insights-popovers--03-plan.jpg"
      },
      {
        "id": "insights-popovers--04-tracker",
        "card": "tracker",
        "title": "The Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 30.92,
        "end": 43.08,
        "thumb": "/videos/thumbs/insights-popovers--04-tracker.jpg"
      },
      {
        "id": "insights-popovers--05-builder",
        "card": "builder",
        "title": "The Builder",
        "description": "Asking is the only thing that moves the count.",
        "t": 43.08,
        "end": 54.1,
        "thumb": "/videos/thumbs/insights-popovers--05-builder.jpg"
      },
      {
        "id": "insights-popovers--06-qr",
        "card": "qr",
        "title": "The QR code",
        "description": "Generated on the page, sized for the till or the door.",
        "t": 54.1,
        "end": 66.16,
        "thumb": "/videos/thumbs/insights-popovers--06-qr.jpg"
      },
      {
        "id": "insights-popovers--07-showcase",
        "card": "showcase",
        "title": "The Showcase",
        "description": "Your best reviews, and what they are worth on your own site.",
        "t": 66.16,
        "end": 76.63,
        "thumb": "/videos/thumbs/insights-popovers--07-showcase.jpg"
      },
      {
        "id": "insights-popovers--08-trial",
        "card": "trial",
        "title": "On a trial",
        "description": "Three days left, and what the trial has found so far.",
        "t": 76.63,
        "end": 83.55,
        "thumb": "/videos/thumbs/insights-popovers--08-trial.jpg"
      },
      {
        "id": "insights-popovers--09-lapsed",
        "card": "lapsed",
        "title": "After it ended",
        "description": "Nine days on, with reviews still arriving and nobody watching.",
        "t": 83.55,
        "end": 89.99,
        "thumb": "/videos/thumbs/insights-popovers--09-lapsed.jpg"
      },
      {
        "id": "insights-popovers--10-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 89.99,
        "end": 93.87,
        "thumb": "/videos/thumbs/insights-popovers--10-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.613,
        "end": 15.957,
        "text": "1. The summary. One headline, one line, and the findings you can open."
      },
      {
        "t": 15.957,
        "end": 20.127,
        "text": "Every finding ends in the thing that fixes it."
      },
      {
        "t": 20.132,
        "end": 30.921,
        "text": "2. The plan, and what auto-reply would have written."
      },
      {
        "t": 30.922,
        "end": 43.083,
        "text": "3. The Tracker. The charts cycle on their own."
      },
      {
        "t": 43.087,
        "end": 54.097,
        "text": "4. The Builder. Asking is the only thing that moves the count."
      },
      {
        "t": 54.1,
        "end": 66.158,
        "text": "5. And the QR code, generated on the page."
      },
      {
        "t": 66.164,
        "end": 76.631,
        "text": "6. The Showcase, and what the reviews are worth."
      },
      {
        "t": 76.633,
        "end": 83.555,
        "text": "7. Three days left on the trial, and what it found."
      },
      {
        "t": 83.557,
        "end": 89.991,
        "text": "8. And nine days after it ended."
      }
    ],
    "tileW": 320,
    "tileH": 180
  },
  {
    "slug": "insights-walkthrough",
    "duration": 82.63,
    "chapters": [
      {
        "id": "insights-walkthrough--01-walkthrough",
        "card": "walkthrough",
        "title": "Insights, page by page",
        "description": "Minus 1 Studios, eight months in. The same numbers on every screen.",
        "t": 0,
        "end": 18.93,
        "thumb": "/videos/thumbs/insights-walkthrough--01-walkthrough.jpg"
      },
      {
        "id": "insights-walkthrough--02-manager",
        "card": "manager",
        "title": "Review Manager",
        "description": "Every review in one inbox, and the plan for the ones waiting.",
        "t": 18.93,
        "end": 35.52,
        "thumb": "/videos/thumbs/insights-walkthrough--02-manager.jpg"
      },
      {
        "id": "insights-walkthrough--03-tracker",
        "card": "tracker",
        "title": "Review Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 35.52,
        "end": 53.01,
        "thumb": "/videos/thumbs/insights-walkthrough--03-tracker.jpg"
      },
      {
        "id": "insights-walkthrough--04-builder",
        "card": "builder",
        "title": "Review Builder",
        "description": "Ask by email, SMS and a code by the till.",
        "t": 53.01,
        "end": 60.42,
        "thumb": "/videos/thumbs/insights-walkthrough--04-builder.jpg"
      },
      {
        "id": "insights-walkthrough--05-showcase",
        "card": "showcase",
        "title": "Review Showcase",
        "description": "Your best reviews on your own website, updating themselves.",
        "t": 60.42,
        "end": 67.27,
        "thumb": "/videos/thumbs/insights-walkthrough--05-showcase.jpg"
      },
      {
        "id": "insights-walkthrough--06-roadmap",
        "card": "roadmap",
        "title": "Insights & Actions",
        "description": "The next three months, one stage at a time.",
        "t": 67.27,
        "end": 78.77,
        "thumb": "/videos/thumbs/insights-walkthrough--06-roadmap.jpg"
      },
      {
        "id": "insights-walkthrough--07-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 78.77,
        "end": 82.63,
        "thumb": "/videos/thumbs/insights-walkthrough--07-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.621,
        "end": 10.837,
        "text": "The hub. One trend per card, and what to do first."
      },
      {
        "t": 10.837,
        "end": 18.934,
        "text": "Each finding is a line you can open, then the thing that fixes it."
      },
      {
        "t": 21.337,
        "end": 30.335,
        "text": "The inbox, and this week's goal above it."
      },
      {
        "t": 30.335,
        "end": 35.516,
        "text": "The plan, and what auto-reply would have written on one of their own reviews."
      },
      {
        "t": 37.922,
        "end": 53.011,
        "text": "The trend, and what moved it."
      },
      {
        "t": 55.415,
        "end": 60.418,
        "text": "Asking is the only thing that moves the count."
      },
      {
        "t": 62.821,
        "end": 67.266,
        "text": "And the best of them belong on your own website."
      },
      {
        "t": 69.669,
        "end": 78.77,
        "text": "All of it as a plan, three stages at a time."
      }
    ],
    "tileW": 320,
    "tileH": 180
  },
  {
    "slug": "the-gap",
    "duration": 51.93,
    "chapters": [
      {
        "id": "the-gap--01-persona-multi",
        "card": "persona-multi",
        "title": "A multi-location brand",
        "description": "Customers compare Hove with Brighton, and their reviews say so.",
        "t": 0,
        "end": 19.36,
        "thumb": "/videos/thumbs/the-gap--01-persona-multi.jpg"
      },
      {
        "id": "the-gap--02-manager",
        "card": "manager",
        "title": "Review Manager",
        "description": "Every review in one inbox, and the plan for the ones waiting.",
        "t": 19.36,
        "end": 31.79,
        "thumb": "/videos/thumbs/the-gap--02-manager.jpg"
      },
      {
        "id": "the-gap--03-tracker",
        "card": "tracker",
        "title": "Review Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 31.79,
        "end": 48.07,
        "thumb": "/videos/thumbs/the-gap--03-tracker.jpg"
      },
      {
        "id": "the-gap--04-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 48.07,
        "end": 51.93,
        "thumb": "/videos/thumbs/the-gap--04-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.628,
        "end": 5.853,
        "text": "Hove looks fine. The lifetime rating is 4.4."
      },
      {
        "t": 5.853,
        "end": 14.397,
        "text": "But the lifetime number cannot move. The last thirty days can."
      },
      {
        "t": 14.397,
        "end": 19.364,
        "text": "Two of the last ten reviews name Brighton as the standard."
      },
      {
        "t": 21.767,
        "end": 31.79,
        "text": "So the plan is about one branch, not the brand."
      },
      {
        "t": 34.199,
        "end": 48.074,
        "text": "The recent window is the number to watch."
      }
    ],
    "tileW": 320,
    "tileH": 180
  },
  {
    "slug": "the-trial",
    "duration": 52.73,
    "chapters": [
      {
        "id": "the-trial--01-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 0,
        "end": 20.95,
        "thumb": "/videos/thumbs/the-trial--01-persona-starter.jpg"
      },
      {
        "id": "the-trial--02-account",
        "card": "account",
        "title": "Subscription and pricing",
        "description": "What the trial got you, what stops, and the way up.",
        "t": 20.95,
        "end": 32.99,
        "thumb": "/videos/thumbs/the-trial--02-account.jpg"
      },
      {
        "id": "the-trial--03-persona-lapsed",
        "card": "persona-lapsed",
        "title": "The trial ended",
        "description": "Reviews still arriving, nobody watching. How do we bring them back?",
        "t": 32.99,
        "end": 48.86,
        "thumb": "/videos/thumbs/the-trial--03-persona-lapsed.jpg"
      },
      {
        "id": "the-trial--04-end",
        "card": "end",
        "title": "Insights exploration",
        "description": "What could be possible with contextual AI insights",
        "t": 48.86,
        "end": 52.73,
        "thumb": "/videos/thumbs/the-trial--04-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.643,
        "end": 7.252,
        "text": "Three days left."
      },
      {
        "t": 7.252,
        "end": 15.582,
        "text": "Four reviews in, none answered."
      },
      {
        "t": 15.582,
        "end": 20.948,
        "text": "And what auto-reply would have written, on one of their own reviews."
      },
      {
        "t": 23.354,
        "end": 32.992,
        "text": "What the trial got them, and what stops."
      },
      {
        "t": 38.458,
        "end": 43.977,
        "text": "Nine days later. Four more reviews, nobody watching."
      },
      {
        "t": 43.977,
        "end": 48.856,
        "text": "So the win-back says exactly that."
      }
    ],
    "tileW": 320,
    "tileH": 180
  }
];
