// GENERATED by scripts/publish-videos.mjs. Do not edit.
// The recorded facts about each video: how long it is, where its sections
// start and end, and every subtitle cue with its timing. The editorial parts
// (title, description, tags, order) live in lib/videos.ts and are keyed by
// slug, so re-publishing a recording never overwrites the writing.

export interface RecordedChapter {
  /** Stable, and also the thumbnail's filename: <flow>--<nn>-<card>. */
  id: string;
  card: string;
  title: string;
  description: string;
  t: number;
  end: number;
  thumb: string;
}

export interface RecordedCue { t: number; end: number; text: string }

export interface RecordedVideo {
  slug: string;
  duration: number;
  chapters: RecordedChapter[];
  transcript: RecordedCue[];
  /** One scrub-preview tile's size on the sprite sheet. */
  tileW: number;
  tileH: number;
}

export const RECORDED: RecordedVideo[] = [
  {
    "slug": "day-one-to-habit",
    "duration": 75.45,
    "chapters": [
      {
        "id": "day-one-to-habit--01-persona-empty",
        "card": "persona-empty",
        "title": "Signed up, looking around",
        "description": "Nothing connected, nothing in. What does the product say to someone with no reviews?",
        "t": 0,
        "end": 14.77,
        "thumb": "/videos/thumbs/day-one-to-habit--01-persona-empty.jpg"
      },
      {
        "id": "day-one-to-habit--02-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 14.77,
        "end": 35.08,
        "thumb": "/videos/thumbs/day-one-to-habit--02-persona-starter.jpg"
      },
      {
        "id": "day-one-to-habit--03-persona-engaged",
        "card": "persona-engaged",
        "title": "A single location, engaged",
        "description": "Campaigns running, replies flowing, and a rating that is hard to move.",
        "t": 35.08,
        "end": 51.16,
        "thumb": "/videos/thumbs/day-one-to-habit--03-persona-engaged.jpg"
      },
      {
        "id": "day-one-to-habit--04-roadmap",
        "card": "roadmap",
        "title": "Insights & Actions",
        "description": "The next three months, one stage at a time.",
        "t": 51.16,
        "end": 59.17,
        "thumb": "/videos/thumbs/day-one-to-habit--04-roadmap.jpg"
      },
      {
        "id": "day-one-to-habit--05-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 59.17,
        "end": 75.45,
        "thumb": "/videos/thumbs/day-one-to-habit--05-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.787,
        "end": 6.23,
        "text": "No reviews, no sites connected, nothing to summarise."
      },
      {
        "t": 6.23,
        "end": 11.563,
        "text": "So it says why it matters, with a number you can cite."
      },
      {
        "t": 11.563,
        "end": 14.774000000000001,
        "text": "And one thing to do today: a code for the till."
      },
      {
        "t": 20.232,
        "end": 24.639,
        "text": "A week in. Four reviews, and a chart that will not lie about them."
      },
      {
        "t": 24.639,
        "end": 35.078,
        "text": "Too few for a trend, so it lists them instead."
      },
      {
        "t": 41.061,
        "end": 51.165,
        "text": "Eight months in, and now the six months mean something."
      },
      {
        "t": 53.569,
        "end": 59.166,
        "text": "Make reviews a habit, not a project."
      }
    ],
    "tileW": 240,
    "tileH": 136
  },
  {
    "slug": "insights-overview",
    "duration": 130.70333,
    "chapters": [
      {
        "id": "insights-overview--01-beacon",
        "card": "beacon",
        "title": "Contextual Insights & Actions",
        "description": "Like someone sat next to you, telling you what to do about your reviews.",
        "t": 0.42333000000000043,
        "end": 4.723330000000001,
        "thumb": "/videos/thumbs/insights-overview--01-beacon.jpg"
      },
      {
        "id": "insights-overview--02-persona-empty",
        "card": "persona-empty",
        "title": "Signed up, looking around",
        "description": "Nothing connected, nothing in. What does the product say to someone with no reviews?",
        "t": 4.723330000000001,
        "end": 18.073330000000002,
        "thumb": "/videos/thumbs/insights-overview--02-persona-empty.jpg"
      },
      {
        "id": "insights-overview--03-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 18.073330000000002,
        "end": 49.71333,
        "thumb": "/videos/thumbs/insights-overview--03-persona-starter.jpg"
      },
      {
        "id": "insights-overview--04-persona-engaged",
        "card": "persona-engaged",
        "title": "A single location, engaged",
        "description": "Campaigns running, replies flowing, and a rating that is hard to move.",
        "t": 49.71333,
        "end": 72.48333000000001,
        "thumb": "/videos/thumbs/insights-overview--04-persona-engaged.jpg"
      },
      {
        "id": "insights-overview--05-persona-multi",
        "card": "persona-multi",
        "title": "A multi-location brand",
        "description": "Customers compare Hove with Brighton, and their reviews say so.",
        "t": 72.48333000000001,
        "end": 92.16333,
        "thumb": "/videos/thumbs/insights-overview--05-persona-multi.jpg"
      },
      {
        "id": "insights-overview--06-persona-lapsed",
        "card": "persona-lapsed",
        "title": "The trial ended",
        "description": "Reviews still arriving, nobody watching. How do we bring them back?",
        "t": 92.16333,
        "end": 105.67333,
        "thumb": "/videos/thumbs/insights-overview--06-persona-lapsed.jpg"
      },
      {
        "id": "insights-overview--07-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 105.67333,
        "end": 130.70333,
        "thumb": "/videos/thumbs/insights-overview--07-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 11.326,
        "end": 18.069,
        "text": "Day one. Nothing connected, nothing in."
      },
      {
        "t": 24.003,
        "end": 27.799,
        "text": "Three days left on the trial."
      },
      {
        "t": 27.799,
        "end": 34.441,
        "text": "What the trial has found so far."
      },
      {
        "t": 34.441,
        "end": 43.234,
        "text": "The plan for the week."
      },
      {
        "t": 43.234,
        "end": 49.711,
        "text": "And what auto-reply would have written, on one of their own reviews."
      },
      {
        "t": 56.438,
        "end": 72.483,
        "text": "Eight months in. What moved, and why."
      },
      {
        "t": 78.456,
        "end": 92.163,
        "text": "Customers compare Hove with Brighton, and their reviews say so."
      },
      {
        "t": 98.103,
        "end": 105.671,
        "text": "Nine days after the trial ended."
      }
    ],
    "tileW": 240,
    "tileH": 136
  },
  {
    "slug": "insights-popovers",
    "duration": 129.64,
    "chapters": [
      {
        "id": "insights-popovers--01-popovers",
        "card": "popovers",
        "title": "What it says when you ask",
        "description": "The eight dialogs, in order, with nothing else in the way.",
        "t": 0,
        "end": 96.96,
        "thumb": "/videos/thumbs/insights-popovers--01-popovers.jpg"
      },
      {
        "id": "insights-popovers--02-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 96.96,
        "end": 129.64,
        "thumb": "/videos/thumbs/insights-popovers--02-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.706,
        "end": 16.075,
        "text": "1. The summary. One headline, one line, and the findings you can open."
      },
      {
        "t": 16.075,
        "end": 20.245,
        "text": "Every finding ends in the thing that fixes it."
      },
      {
        "t": 20.245,
        "end": 32.042,
        "text": "2. The plan, and what auto-reply would have written."
      },
      {
        "t": 32.042,
        "end": 44.181,
        "text": "3. The Tracker. The charts cycle on their own."
      },
      {
        "t": 44.181,
        "end": 55.437,
        "text": "4. The Builder. Asking is the only thing that moves the count."
      },
      {
        "t": 55.437,
        "end": 67.554,
        "text": "5. And the QR code, generated on the page."
      },
      {
        "t": 67.554,
        "end": 81.403,
        "text": "6. The Showcase, and what the reviews are worth."
      },
      {
        "t": 81.403,
        "end": 91.328,
        "text": "7. Three days left on the trial, and what it found."
      },
      {
        "t": 91.328,
        "end": 96.961,
        "text": "8. And nine days after it ended."
      }
    ],
    "tileW": 240,
    "tileH": 136
  },
  {
    "slug": "insights-walkthrough",
    "duration": 99.85,
    "chapters": [
      {
        "id": "insights-walkthrough--01-walkthrough",
        "card": "walkthrough",
        "title": "Insights, page by page",
        "description": "Minus 1 Studios, eight months in. The same numbers on every screen.",
        "t": 0,
        "end": 19.13,
        "thumb": "/videos/thumbs/insights-walkthrough--01-walkthrough.jpg"
      },
      {
        "id": "insights-walkthrough--02-manager",
        "card": "manager",
        "title": "Review Manager",
        "description": "Every review in one inbox, and the plan for the ones waiting.",
        "t": 19.13,
        "end": 35.93,
        "thumb": "/videos/thumbs/insights-walkthrough--02-manager.jpg"
      },
      {
        "id": "insights-walkthrough--03-tracker",
        "card": "tracker",
        "title": "Review Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 35.93,
        "end": 53.38,
        "thumb": "/videos/thumbs/insights-walkthrough--03-tracker.jpg"
      },
      {
        "id": "insights-walkthrough--04-builder",
        "card": "builder",
        "title": "Review Builder",
        "description": "Ask by email, SMS and a code by the till.",
        "t": 53.38,
        "end": 61.38,
        "thumb": "/videos/thumbs/insights-walkthrough--04-builder.jpg"
      },
      {
        "id": "insights-walkthrough--05-showcase",
        "card": "showcase",
        "title": "Review Showcase",
        "description": "Your best reviews on your own website, updating themselves.",
        "t": 61.38,
        "end": 68.72,
        "thumb": "/videos/thumbs/insights-walkthrough--05-showcase.jpg"
      },
      {
        "id": "insights-walkthrough--06-roadmap",
        "card": "roadmap",
        "title": "Insights & Actions",
        "description": "The next three months, one stage at a time.",
        "t": 68.72,
        "end": 80.65,
        "thumb": "/videos/thumbs/insights-walkthrough--06-roadmap.jpg"
      },
      {
        "id": "insights-walkthrough--07-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 80.65,
        "end": 99.85,
        "thumb": "/videos/thumbs/insights-walkthrough--07-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.7039999999999997,
        "end": 10.928,
        "text": "The hub. One trend per card, and what to do first."
      },
      {
        "t": 10.928,
        "end": 19.129,
        "text": "Each finding is a line you can open, then the thing that fixes it."
      },
      {
        "t": 21.539,
        "end": 30.747,
        "text": "The inbox, and this week's goal above it."
      },
      {
        "t": 30.747,
        "end": 35.929,
        "text": "The plan, and what auto-reply would have written on one of their own reviews."
      },
      {
        "t": 38.339,
        "end": 53.38,
        "text": "The trend, and what moved it."
      },
      {
        "t": 55.787,
        "end": 61.384,
        "text": "Asking is the only thing that moves the count."
      },
      {
        "t": 63.796,
        "end": 68.724,
        "text": "And the best of them belong on your own website."
      },
      {
        "t": 71.14,
        "end": 80.65,
        "text": "All of it as a plan, three stages at a time."
      }
    ],
    "tileW": 240,
    "tileH": 136
  },
  {
    "slug": "the-gap",
    "duration": 66.1,
    "chapters": [
      {
        "id": "the-gap--01-persona-multi",
        "card": "persona-multi",
        "title": "A multi-location brand",
        "description": "Customers compare Hove with Brighton, and their reviews say so.",
        "t": 0,
        "end": 19.87,
        "thumb": "/videos/thumbs/the-gap--01-persona-multi.jpg"
      },
      {
        "id": "the-gap--02-manager",
        "card": "manager",
        "title": "Review Manager",
        "description": "Every review in one inbox, and the plan for the ones waiting.",
        "t": 19.87,
        "end": 32.88,
        "thumb": "/videos/thumbs/the-gap--02-manager.jpg"
      },
      {
        "id": "the-gap--03-tracker",
        "card": "tracker",
        "title": "Review Tracker",
        "description": "The trend across every review site, and what moved it.",
        "t": 32.88,
        "end": 49.33,
        "thumb": "/videos/thumbs/the-gap--03-tracker.jpg"
      },
      {
        "id": "the-gap--04-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 49.33,
        "end": 66.1,
        "thumb": "/videos/thumbs/the-gap--04-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.844,
        "end": 6.064,
        "text": "Hove looks fine. The lifetime rating is 4.4."
      },
      {
        "t": 6.064,
        "end": 14.781,
        "text": "But the lifetime number cannot move. The last thirty days can."
      },
      {
        "t": 14.781,
        "end": 19.865,
        "text": "Two of the last ten reviews name Brighton as the standard."
      },
      {
        "t": 22.286,
        "end": 32.882,
        "text": "So the plan is about one branch, not the brand."
      },
      {
        "t": 35.286,
        "end": 49.33,
        "text": "The recent window is the number to watch."
      }
    ],
    "tileW": 240,
    "tileH": 136
  },
  {
    "slug": "the-trial",
    "duration": 67.42,
    "chapters": [
      {
        "id": "the-trial--01-persona-starter",
        "card": "persona-starter",
        "title": "On a free trial",
        "description": "Google connected, four reviews in, nobody answered. The trial has to earn its keep.",
        "t": 0,
        "end": 22.04,
        "thumb": "/videos/thumbs/the-trial--01-persona-starter.jpg"
      },
      {
        "id": "the-trial--02-account",
        "card": "account",
        "title": "Subscription and pricing",
        "description": "What the trial got you, what stops, and the way up.",
        "t": 22.04,
        "end": 35.03,
        "thumb": "/videos/thumbs/the-trial--02-account.jpg"
      },
      {
        "id": "the-trial--03-persona-lapsed",
        "card": "persona-lapsed",
        "title": "The trial ended",
        "description": "Reviews still arriving, nobody watching. How do we bring them back?",
        "t": 35.03,
        "end": 52.33,
        "thumb": "/videos/thumbs/the-trial--03-persona-lapsed.jpg"
      },
      {
        "id": "the-trial--04-end",
        "card": "end",
        "title": "Someone sat next to you",
        "description": "Telling you what to do about your reviews, in your own numbers.",
        "t": 52.33,
        "end": 67.42,
        "thumb": "/videos/thumbs/the-trial--04-end.jpg"
      }
    ],
    "transcript": [
      {
        "t": 2.694,
        "end": 7.321,
        "text": "Three days left."
      },
      {
        "t": 7.321,
        "end": 16.678,
        "text": "Four reviews in, none answered."
      },
      {
        "t": 16.678,
        "end": 22.038,
        "text": "And what auto-reply would have written, on one of their own reviews."
      },
      {
        "t": 24.44,
        "end": 35.027,
        "text": "What the trial got them, and what stops."
      },
      {
        "t": 40.48,
        "end": 46.427,
        "text": "Nine days later. Four more reviews, nobody watching."
      },
      {
        "t": 46.427,
        "end": 52.331,
        "text": "So the win-back says exactly that."
      }
    ],
    "tileW": 240,
    "tileH": 136
  }
];
