// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const AiChatContract = contract({
  name: "AiChat",
  description: "A pre-built chat block — paste it in to get a working LLM chat surface without composing the message list, autoscroll, suggested prompts, and submit input yourself. Reach for it as the \"AI panel\" in an admin/support tool, or to demo an LLM-driven feature inside a marketing page. For Studio-grade chat with file refs and streaming structured output, you'll outgrow this and want a custom composition built on Textarea + Card + ScrollArea.",
  import: "@gradeui/ui",
  aliases: ["ai chat","chat panel","chat block","llm chat","assistant panel","copilot chat"],
  composesWith: ["Card (host in a sidebar panel)","Sheet (mobile drawer)","Stack (place above other content)"],
  props: {
  "messages": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "`{ id, role: \"user\" | \"assistant\", content, timestamp }`; defaults to empty",
  },
  "onSendMessage": {
      schema: z.unknown().optional(),
      design: "event",
      description: "fires when the user submits a query",
  },
  "isLoading": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "shows a typing indicator on the last assistant turn",
  },
  "placeholder": {
      schema: z.string().optional(),
      design: "content",
      description: "input placeholder text",
  },
  "suggestedPrompts": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "empty-state quick prompts",
  },
  "className": {
      schema: z.string().optional(),
      design: "plumbing",
  },
  },
});
