// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const AvatarContract = contract({
  name: "Avatar",
  description: "User/entity identity for PEOPLE — profile pictures, author rows, member lists, account headers. Circular by default; the AvatarFallback initials read as a person's name. Always include AvatarFallback so load failure doesn't leave a gap.",
  import: "@gradeui/ui",
  aliases: ["profile picture","user image","account image","avatar","person glyph","user avatar","profile image","react native avatar"],
  subcomponents: ["AvatarImage","AvatarFallback"],
  composesWith: ["Card (in CardHeader)","Table cells","Badge (placed next to for status)","Skeleton (loading state)"],
  styleDefaults: {"AvatarImage":"aspect-square h-full w-full"},
  props: {
  "className": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "set size via utilities (default h-10 w-10)",
  },
  "src": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "initials": {
      schema: z.unknown(),
      design: "plumbing",
  },
  },
});
