// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const ButtonContract = contract({
  name: "Button",
  description: "Any clickable action. Use size=\"icon\" for square icon-only buttons, variant=\"link\" for inline links that should look like Button. A Button placed next to a TabsList of the same size lines up edge-to-edge without per-call overrides.",
  import: "@gradeui/ui",
  aliases: ["button","push button","plain button","bordered button","destructive button","capsule button","link button","action button","cta"],
  composesWith: ["Dialog","DropdownMenu","Tooltip","Card (in CardFooter)","Row","Form controls"],
  props: {
  "variant": {
      schema: z.unknown().optional(),
      design: "plumbing",
  },
  "size": {
      schema: z.enum(["sm", "md", "lg", "icon"]).optional(),
      design: "knob",
      description: "t-shirt scale aligned with Tabs/ToggleGroup heights (sm=h-7, md=h-8, lg=h-10). `default` still works as an alias for `md`.",
  },
  "asChild": {
      schema: z.boolean().optional(),
      design: "plumbing",
      description: "renders as the child element (use to wrap <a>/<Link>)",
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  },
});
