// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const CardContract = contract({
  name: "Card",
  description: "Grouped content with a distinct surface — settings panels, dashboard tiles, list-of-cards layouts. Pair CardHeader (title + description) with CardContent and optional CardFooter (actions).",
  import: "@gradeui/ui",
  aliases: ["card","group box","groupbox","panel","tile","surface"],
  subcomponents: ["CardHeader","CardTitle","CardDescription","CardContent","CardFooter"],
  composesWith: ["Button (in CardFooter)","Badge","Separator","Avatar","any form controls"],
  props: {
  "Each": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "No": {
      schema: z.unknown(),
      design: "plumbing",
      description: "Card is a flexible container surface",
  },
  },
});
