// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const CardContract = contract({
  name: "Card",
  description: "Grouped content with a distinct surface — settings panels, dashboard tiles, list-of-cards layouts, marketing hero containers, AI suggestion overlays. Pair CardHeader (title + description) with CardContent and optional CardFooter (actions). Reach for `surface=\"glass\"` whenever the card sits over a busy backdrop (gradient mesh, dot grid, generative art, image hero).",
  import: "@gradeui/ui",
  aliases: ["card","group box","groupbox","panel","tile","surface","glass card","frosted card","floating panel","hero card","ai suggestion card","dashboard tile","settings panel"],
  subcomponents: ["CardHeader","CardTitle","CardDescription","CardContent","CardFooter"],
  element: "div",
  composesWith: ["Button (in CardFooter)","Badge","Separator","Avatar","Code","MediaSurface","any form controls"],
  styleDefaults: {"Card":"gds-card rounded-xl border text-card-foreground shadow","CardHeader":"flex flex-col space-y-1.5 p-6","CardTitle":"font-semibold leading-none tracking-tight","CardDescription":"text-sm text-muted-foreground","CardContent":"p-6 pt-0","CardFooter":"flex items-center p-6 pt-0"},
  props: {
  "surface": {
      schema: z.enum(["solid", "translucent", "glass", "glass-strong"]).optional(),
      design: "knob",
      description: "what the card surface is *made of*. `solid` is the default opaque `bg-card`. `translucent` is ~82% opacity for menu sheets. `glass` is ~58% opacity + 14px blur + edge highlight for floating panels. `glass-strong` is ~42% + 24px blur for full-page overlays. Composes with `shadow-elevation-*` (depth) and `gds-aura-*` (state signal).",
  },
  "interactive": {
      schema: z.enum(["boolean"]).optional(),
      design: "knob",
      description: "the WHOLE card is the click target (a wallet tile, a project row). Adds the pointer, keyboard focusability and a hover/focus treatment, and lights any trailing Button inside at the same moment so the card and its chevron read as ONE affordance. On dark surfaces a drop shadow barely registers, so the hover cue leads with a one-step surface lift (card -> muted) plus a brighter border, with the shadow as a secondary hint. Put the handler on the card and make the trailing chevron a `Button asChild` wrapping a span, so there is no nested control inside a clickable region.",
  },
  },
});
