// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const CheckboxContract = contract({
  name: "Checkbox",
  description: "Binary on/off tied to a list (select multiple, agree to terms). Single on/off that controls a setting is better with Switch.",
  import: "@gradeui/ui",
  aliases: ["checkbox","tickbox","tick box","check","multi-select item"],
  composesWith: ["Label (via htmlFor)","Card","Form rows","Table (for row selection)"],
  props: {
  "checked": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "onCheckedChange": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "defaultChecked": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "id": {
      schema: z.string().optional(),
      design: "plumbing",
      description: "bind a Label's htmlFor to this",
  },
  },
});
