// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const ComboboxContract = contract({
  name: "Combobox",
  description: "Single-pick searchable picker — the single-select sibling of MultiSelect and the Linear \"selectable badge\" pattern (status / priority / assignee). Use triggerVariant=\"inline\" with renderValue returning a Badge to make a value read as a clickable token that opens a command menu. For multiple selection use MultiSelect; for a small fixed list with no search use Select; for free-form command palettes use Command directly. Pass disabled (driven by a permission check) to show the value without letting the user edit it.",
  import: "@gradeui/ui",
  aliases: ["combobox","single select","searchable select","picker","status picker","priority picker","assignee picker","command select","autocomplete","dropdown select","selectable badge","inline select","token select","linear combobox"],
  composesWith: ["Popover","Command","Badge","Avatar","PropertyList","Table","Field"],
  styleDefaults: {"Combobox":"ring-offset-background focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"},
  props: {
  "options": {
      schema: z.unknown(),
      design: "plumbing",
      description: "the selectable pool",
  },
  "value": {
      schema: z.string().optional(),
      design: "content",
      description: "controlled selection (wire onValueChange)",
  },
  "defaultValue": {
      schema: z.string().optional(),
      design: "content",
      description: "uncontrolled initial selection",
  },
  "onValueChange": {
      schema: z.unknown().optional(),
      design: "event",
      description: "fired with the next value, or null when cleared",
  },
  "placeholder": {
      schema: z.string().optional(),
      design: "content",
      description: "trigger text when nothing is selected",
  },
  "searchPlaceholder": {
      schema: z.string().optional(),
      design: "content",
      description: "search-input placeholder",
  },
  "emptyMessage": {
      schema: z.string().optional(),
      design: "content",
      description: "shown when search returns no rows",
  },
  "searchable": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "show the search input (default true)",
  },
  "clearable": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "add a Clear row so the value can return to unset",
  },
  "triggerVariant": {
      schema: z.enum(["default", "inline"]).optional(),
      design: "knob",
      description: "default = form-control surface (like Select); inline = chrome-free token trigger",
  },
  "renderValue": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "render the selected value yourself (e.g. a Badge); falls back to icon + label",
  },
  "hideChevron": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "drop the trailing chevron (inline token look)",
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "lock to a read-only display of the current value",
  },
  "align": {
      schema: z.enum(["start", "center", "end"]).optional(),
      design: "knob",
      description: "popover alignment",
  },
  },
});
