// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const CommandContract = contract({
  name: "Command",
  description: "A searchable list of actions or destinations — global ⌘K palettes, \"jump to\" inputs, account switchers with filter. Wrap in CommandDialog when it should pop over the entire app on a hotkey. For straight forms with filter, prefer a Select with a search input. For free-text autocomplete tied to a single value, prefer Combobox built on Popover + Command.",
  import: "@gradeui/ui",
  aliases: ["command palette","command menu","cmd k","quick switcher","action menu","spotlight","spotlight search","quick open","fuzzy finder"],
  subcomponents: ["CommandInput","CommandList","CommandEmpty","CommandGroup","CommandItem","CommandSeparator","CommandShortcut","CommandDialog"],
  composesWith: ["Dialog (CommandDialog wraps it)","Popover (inline combobox)","Tooltip"],
  props: {
  "value": {
      schema: z.string().optional(),
      design: "content",
      description: "controlled active item value",
  },
  "onValueChange": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "placeholder": {
      schema: z.string().optional(),
      design: "content",
  },
  "children": {
      schema: z.unknown(),
      design: "plumbing",
      description: "wraps groups and empty state",
  },
  "heading": {
      schema: z.string().optional(),
      design: "content",
  },
  "onSelect": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "open": {
      schema: z.unknown(),
      design: "plumbing",
      description: "when you want the command palette mounted in a modal (cmd+k pattern)",
  },
  },
});
