// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const DropdownMenuContract = contract({
  name: "DropdownMenu",
  description: "A small action menu attached to a trigger — overflow \"…\" buttons on cards, user-avatar menus in headers, \"Insert\" menus in editors. For a full searchable list, use Command. For ONE primary action plus a secondary, use a Button next to a smaller ghost Button instead of a dropdown.",
  import: "@gradeui/ui",
  aliases: ["dropdown","dropdown menu","overflow menu","kebab menu","more menu","action menu","context-style menu","menu","pull-down menu","pulldown menu","context menu","popup menu","actions menu","glass menu","frosted menu","ios menu","hig menu"],
  subcomponents: ["DropdownMenuTrigger","DropdownMenuContent","DropdownMenuItem","DropdownMenuCheckboxItem","DropdownMenuRadioGroup","DropdownMenuRadioItem","DropdownMenuLabel","DropdownMenuSeparator","DropdownMenuShortcut","DropdownMenuGroup","DropdownMenuSub","DropdownMenuSubTrigger","DropdownMenuSubContent"],
  composesWith: ["Button (as trigger asChild)","Avatar (user menu)","Card (overflow on a tile)","Tooltip (on the trigger)"],
  props: {
  "open": {
      schema: z.unknown().optional(),
      design: "plumbing",
  },
  "asChild": {
      schema: z.boolean().optional(),
      design: "plumbing",
      description: "usually wraps a Button",
  },
  "align": {
      schema: z.enum(["start", "center", "end", "top", "right", "bottom", "left"]).optional(),
      design: "knob",
  },
  "surface": {
      schema: z.enum(["solid", "translucent", "glass", "glass-strong"]).optional(),
      design: "knob",
      description: "what the menu surface is *made of*. `solid` (default) is `bg-popover`. `translucent` matches Apple HIG / iOS menu sheets. `glass` for menus floating over rich canvases.",
  },
  "size": {
      schema: z.enum(["default", "sm", "xs"]).optional(),
      design: "knob",
      description: "menu density; cascades to every item (Item, Checkbox, Radio, SubTrigger, Label) via context so a compact trigger gets a compact menu. Use \"xs\" in dense tool panels.",
  },
  "onSelect": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "DropdownMenuCheckboxItem": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "DropdownMenuSub": {
      schema: z.unknown(),
      design: "plumbing",
      description: "sub-trigger shows children, sub-content holds the deeper items",
  },
  "children": {
      schema: z.unknown(),
      design: "plumbing",
      description: "right-aligned kbd hint",
  },
  },
});
