// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const FieldContract = contract({
  name: "Field",
  description: "Pair a bare control with a label and optional description in a row, with id + aria-describedby wired automatically. Use layout=\"setting\" for the classic settings row (label on the left, Switch on the right). For a selectable CARD where the whole surface is the control, use RadioCard / CheckboxCard / SwitchCard instead.",
  import: "@gradeui/ui",
  aliases: ["field","form field","control row","label and description","two line checkbox","option row","setting row","toggle row"],
  composesWith: ["Checkbox","RadioGroup","RadioGroupItem","Switch","Badge (inside Field.Trailing)"],
  props: {
  "layout": {
      schema: z.enum(["option", "setting"]).optional(),
      design: "knob",
      description: "option (default): control leads, text beside it; setting: text leads, control pinned trailing",
  },
  "children": {
      schema: z.unknown(),
      design: "plumbing",
      description: "order does not matter",
  },
  },
});
