// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const InputGroupContract = contract({
  name: "InputGroup",
  description: "Compose an input with leading/trailing icons, text affixes, buttons, or a toolbar inside one bordered field. Put controls in InputGroupInput / InputGroupTextarea and decorations in InputGroupAddon. For a plain field with a label + description, use Field instead.",
  import: "@gradeui/ui",
  aliases: ["input group","input with icon","input addon","prefix suffix input","search input","input affix","text field with button","leading icon input","trailing button input"],
  subcomponents: ["InputGroupInput","InputGroupTextarea","InputGroupAddon","InputGroupButton","InputGroupText"],
  element: "div",
  subcomponentElements: {"InputGroupInput":"input","InputGroupTextarea":"textarea","InputGroupButton":"button","InputGroupText":"span"},
  composesWith: ["Input","Textarea","Button","Field","Label","Kbd","Tooltip"],
  styleDefaults: {"InputGroup":"group/input-group relative flex w-full items-center rounded-md border border-input shadow-xs transition-[color,box-shadow] outline-none dark:bg-input/30","InputGroupAddon":"flex h-auto cursor-text items-center justify-center gap-2 py-1.5 text-sm font-medium text-muted-foreground select-none group-data-[disabled=true]/input-group:opacity-50 [&>kbd]:rounded-[calc(var(--radius)-5px)] [&>svg:not([class*='size-'])]:size-4 order-first pl-3 has-[>button]:ml-[-0.45rem] has-[>kbd]:ml-[-0.35rem]","InputGroupButton":"flex items-center gap-2 text-sm shadow-none h-6 gap-1 rounded-[calc(var(--radius)-5px)] px-2 has-[>svg]:px-2 [&>svg:not([class*='size-'])]:size-3.5","InputGroupText":"flex items-center gap-2 text-sm text-muted-foreground [&_svg]:pointer-events-none [&_svg:not([class*='size-'])]:size-4","InputGroupInput":"flex-1 rounded-none border-0 bg-transparent shadow-none focus-visible:ring-0 dark:bg-transparent","InputGroupTextarea":"flex-1 resize-none rounded-none border-0 bg-transparent py-3 shadow-none focus-visible:ring-0 dark:bg-transparent"},
  props: {
  "align": {
      schema: z.enum(["inline-start", "inline-end", "block-start", "block-end"]).optional(),
      design: "knob",
      description: "a slot for icons / text / buttons. inline = beside the control; block = stacked above/below (toolbars, textareas).",
  },
  "variant": {
      schema: z.unknown().optional(),
      design: "plumbing",
  },
  "size": {
      schema: z.enum(["xs", "sm", "icon-xs", "icon-sm"]).optional(),
      design: "knob",
      description: "a compact button sized for addons (wraps Button).",
  },
  },
});
