// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const InputContract = contract({
  name: "Input",
  description: "Any single-line text entry. Always pair with a Label for accessibility. Use startSlot/endSlot for icons, prefixes and units instead of hand-positioning absolute children; use size=\"sm\"/\"xs\" in dense tool panels.",
  import: "@gradeui/ui",
  aliases: ["text field","textbox","textfield","form field","text input","secure field","search field","url field","number field","textinput","text input field","react native textinput","unit input","input with icon"],
  composesWith: ["Label","Form","Card (in CardContent)","Button (form submit)"],
  styleDefaults: {"Input":"flex w-full rounded-md border border-input bg-transparent shadow-sm transition-colors file:border-0 file:bg-transparent file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 h-9 pl-3 pr-3 py-1 text-base file:text-sm md:text-sm"},
  variantDefaults: {"size":"default"},
  props: {
  "type": {
      schema: z.string().optional(),
      design: "content",
  },
  "size": {
      schema: z.enum(["default", "sm", "xs"]).optional(),
      design: "knob",
      description: "control density. `default` (h-9) for forms; `sm` (h-8) and `xs` (h-7) for dense tool panels like the inspector.",
  },
  "startSlot": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "adornment rendered inside the leading edge (icon, prefix, currency symbol). Non-interactive by default so clicks focus the input.",
  },
  "endSlot": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "adornment rendered inside the trailing edge (unit like \"px\", a clear button, a stepper). Same pointer rules as startSlot.",
  },
  },
});
