// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const InputContract = contract({
  name: "Input",
  description: "Any single-line text entry. Always pair with a Label for accessibility.",
  import: "@gradeui/ui",
  aliases: ["text field","textbox","textfield","form field","text input","secure field","search field","url field","number field","textinput","text input field","react native textinput"],
  composesWith: ["Label","Form","Card (in CardContent)","Button (form submit)"],
  props: {
  "type": {
      schema: z.string().optional(),
      design: "content",
  },
  },
});
