// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const LogoContract = contract({
  name: "Logo",
  description: "A brand mark with built-in variations — a square mark for tight",
  import: "@gradeui/ui",
  aliases: ["logo","brand","brandmark","wordmark","lockup","brand logo","app logo","logotype"],
  composesWith: ["AppShell","AppShellHeader","Sidebar","SidebarHeader","Row","Stack"],
  styleDefaults: {"Logo":"gds-logo inline-flex shrink-0 select-none items-center","LogoPlaceholder":"inline-flex h-full items-center gap-1.5 rounded-md border border-dashed px-2 text-xs font-medium"},
  props: {
  "sources": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "artwork keyed by lockup then appearance:",
  },
  },
});
