// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const MultiSelectContract = contract({
  name: "MultiSelect",
  description: "Picking multiple items from a finite list — tag selectors, filter chips, \"share with N people\", multi-region settings. The trigger renders the current selection as removable Badges so the choice is always visible. For SINGLE selection use Select. For huge unbounded sets (users, autocompleted email addresses) reach for Command directly with custom rendering.",
  import: "@gradeui/ui",
  aliases: ["multi select","multiselect","multi-select","tag picker","chips input","multi picker","multi-pick combobox","multipicker","tag select","react native multi select","multi-select combobox"],
  composesWith: ["Popover","Command","Badge","Checkbox-style row indicator","Separator"],
  props: {
  "options": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "value": {
      schema: z.string().optional(),
      design: "content",
      description: "controlled selection",
  },
  "defaultValue": {
      schema: z.string().optional(),
      design: "content",
      description: "uncontrolled initial selection",
  },
  "onValueChange": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "placeholder": {
      schema: z.string().optional(),
      design: "content",
      default: "Select…",
  },
  "searchPlaceholder": {
      schema: z.string().optional(),
      design: "content",
      default: "Search…",
  },
  "emptyMessage": {
      schema: z.string().optional(),
      design: "content",
      default: "Nothing matches.",
  },
  "maxCount": {
      schema: z.number().optional(),
      design: "knob",
      description: "badges shown on the trigger before collapsing to \"+N more\"",
  },
  "searchable": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "hide for short option lists",
      default: true,
  },
  "badgeDismissible": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "show × on each selected badge",
      default: true,
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "modalPopover": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "Popover modal mode",
      default: false,
  },
  "className": {
      schema: z.string().optional(),
      design: "plumbing",
  },
  },
});
