// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const ResizableContract = contract({
  name: "Resizable",
  description: "A multi-pane layout where the user wants to drag the divider — Slack/Mail-style list+detail, IDE editor+terminal, side-by-side compare view. Static layouts shouldn't use this — reach for AppShell with nav=\"three-pane\" (fixed widths) or Grid (responsive ladder). Built on react-resizable-panels under the hood.",
  import: "@gradeui/ui",
  aliases: ["resizable","splitter","split pane","drag divider","adjustable panels","resizer","split view","draggable divider","split pane resizer","ns split view"],
  subcomponents: ["ResizablePanelGroup","ResizablePanel","ResizableHandle"],
  composesWith: ["AppShellMain (host the splitter inside main)","ScrollArea (each panel's content)","Card"],
  props: {
  "direction": {
      schema: z.enum(["horizontal", "vertical"]),
      design: "knob",
      description: "required; sets the axis the user drags along",
  },
  "autoSaveId": {
      schema: z.string().optional(),
      design: "content",
      description: "persists user-adjusted sizes to localStorage under this id",
  },
  "onLayout": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "defaultSize": {
      schema: z.number().optional(),
      design: "knob",
      description: "percent of group (0-100); siblings should sum to ~100",
  },
  "minSize": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "percent bounds",
  },
  "collapsible": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "allow this panel to collapse to zero",
  },
  "collapsedSize": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "collapse behaviour controls",
  },
  "withHandle": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "show a visible drag affordance (default just a hit-zone)",
  },
  },
});
