// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const SelectContract = contract({
  name: "Select",
  description: "Single-choice from 3+ known options. Fewer than 3 → RadioGroup. Huge list with search → use a Combobox (not in DS yet). Multi-select → not supported by this primitive.",
  import: "@gradeui/ui",
  aliases: ["dropdown","combobox","picker","select","pop-up button","popup button","popup picker","picker view","rnpickerselect","react native picker","native picker"],
  subcomponents: ["SelectTrigger","SelectValue","SelectContent","SelectItem","SelectGroup","SelectLabel","SelectSeparator"],
  composesWith: ["Label (above SelectTrigger)","Form","Card"],
  props: {
  "value": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "Radix root",
  },
  "wraps": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "placeholder": {
      schema: z.string().optional(),
      design: "content",
      description: "text when nothing is selected",
  },
  "accepts": {
      schema: z.unknown(),
      design: "plumbing",
  },
  },
});
