// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const SidebarContract = contract({
  name: "Sidebar",
  description: "Vertical app navigation. Drop inside `<AppShellNav placement=\"side\">` for full-page layouts. Compound API — `<SidebarHeader>` for brand, `<SidebarContent>` for the scrollable body of `<SidebarSection>` + `<SidebarItem>` rows, `<SidebarFooter>` for user / settings chrome. For top nav reach for TopMenu; for command-palette style search reach for Command.",
  import: "@gradeui/ui",
  aliases: ["sidebar","side menu","sidemenu","navigation sidebar","app sidebar","side nav","side nav rail","master pane","sidebarmenu","navigation rail","react native drawer"],
  subcomponents: ["SidebarHeader","SidebarContent","SidebarFooter","SidebarSection","SidebarItem"],
  composesWith: ["AppShell (inside AppShellNav)","Avatar (in Footer)","Tooltip (auto-wrapped on collapsed items)","Button (asChild for custom routing)"],
  props: {
  "collapsed": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "controlled collapsed state (wire onCollapsedChange when set)",
  },
  "defaultCollapsed": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "uncontrolled initial value (default false)",
  },
  "onCollapsedChange": {
      schema: z.unknown().optional(),
      design: "event",
  },
  "collapsible": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "show the affordance for the user to collapse (default true)",
  },
  "variant": {
      schema: z.enum(["rail", "panel"]).optional(),
      design: "knob",
      description: "outer chrome — `rail` (default) sits flush against an adjacent surface with a single right-border + tracked width; `panel` is a card-style floating sidebar with full border + rounded corners and width inherited from the parent flex/grid track.",
  },
  "any": {
      schema: z.unknown(),
      design: "plumbing",
      description: "brand / logo / org switcher; hides nothing when collapsed (centred)",
  },
  "title": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "group label; **uppercase tracking-wide muted** styling auto-applied (Notion / Linear / Slack-style \"GAMES\", \"FAVORITES\", \"WORKSPACE\" headers); hidden when sidebar is collapsed",
  },
  "icon": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "optional icon beside the title",
  },
  "trailing": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "Right-edge action slot. On **SidebarSection**: the canonical \"+\" / \"...\" header affordance (Notion's \"+ Add page\", Linear's \"+\" next to Favorites). On **SidebarTreeItem**: a sibling-of-button slot for settings cog / more-actions / '+ add child'; vertically centered against the row; click events stopPropagation'd so taps don't toggle expand. Branch row exposes `group/row` named-group, so consumer can use `hidden group-hover/row:flex` for hover-only visibility scoped to the branch alone.",
  },
  "defaultExpanded": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "initial open state (default true)",
  },
  "badge": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "trailing count / label (hidden when collapsed)",
  },
  "active": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "current route; adds aria-current=\"page\"",
  },
  "href": {
      schema: z.string().optional(),
      design: "content",
      description: "renders as <a>; for routing use `asChild` with your link component",
  },
  "asChild": {
      schema: z.boolean().optional(),
      design: "plumbing",
      description: "wrap a custom link (<Link href> from Next.js etc.) via Radix Slot",
  },
  "asButton": {
      schema: z.boolean().optional(),
      design: "knob",
      description: "render as <button> for action rows (open dialog, log out)",
  },
  "disabled": {
      schema: z.boolean().optional(),
      design: "knob",
  },
  "collapsedLabel": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "tooltip override when sidebar is collapsed (defaults to children text)",
  },
  "size": {
      schema: z.enum(["sm", "md"]).optional(),
      design: "knob",
      description: "row size — `md` (default) is the standard `text-sm font-medium` nav row; `sm` is `text-xs` + lighter weight + tighter padding for visually subordinate rows (nested screens, sub-pages). Active state still wins on color + weight.",
  },
  "description": {
      schema: z.unknown().optional(),
      design: "plumbing",
      description: "secondary line under the label — `Edited 2m ago`, `12 items`, etc. Layout stacks label + description; icon vertically centered against stack; badge stays trailing. Hidden when sidebar collapsed.",
  },
  },
});
