// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const TableContract = contract({
  name: "Table",
  description: "Structured tabular data — rows × columns with alignment requirements. NOT a layout grid — for that use div+Tailwind grid utilities. Keep to <100 rows; larger datasets need virtualisation (not in DS).",
  import: "@gradeui/ui",
  aliases: ["table","table view","data table","datatable","grid view","data grid","rows and columns"],
  subcomponents: ["TableHeader","TableBody","TableFooter","TableRow","TableHead","TableCell","TableCaption"],
  composesWith: ["Card (wrap the table)","Badge (inside TableCell for status)","Checkbox (row selection)","Button (row actions)"],
  props: {
  "Each": {
      schema: z.unknown(),
      design: "plumbing",
  },
  "No": {
      schema: z.unknown(),
      design: "plumbing",
      description: "styling follows the active theme tokens",
  },
  },
});
