// AUTO-GENERATED by scripts/generate-contracts.mjs from the .md sidecar.
// Hand edits will be overwritten on the next run. To customise this
// component's contract (add actions, structured props, custom control
// kinds, glyph pickers), remove this file's auto-generated marker and
// hand-author it — the generator skips files without the marker.

import { z } from "zod";
import { contract } from "@gradeui/contracts";

export const TooltipContract = contract({
  name: "Tooltip",
  description: "A short, non-essential label that explains a control on hover/focus — icon-only buttons in toolbars, abbreviated column headers, status dots. NEVER hide critical info inside a tooltip — they're invisible on touch and can be skipped by screen readers if implemented carelessly. For richer hover content use HoverCard. For inline help text that's always visible, use a description paragraph.",
  import: "@gradeui/ui",
  aliases: ["tooltip","tip","hover tip","hint","label on hover","help tag","hint","helper text bubble","info tip"],
  subcomponents: ["TooltipTrigger","TooltipContent","TooltipProvider"],
  composesWith: ["Button (icon-only)","Toggle","TabsTrigger (the canonical tabs already have a `tooltip` prop that wraps this)","Avatar (status badge meaning)"],
  props: {
  "delayDuration": {
      schema: z.number().optional(),
      design: "knob",
      description: "ms hover before show; mount ONCE near the app root",
  },
  "skipDelayDuration": {
      schema: z.number().optional(),
      design: "knob",
      description: "ms gap that still feels like \"same hover\"",
  },
  "open": {
      schema: z.unknown().optional(),
      design: "plumbing",
  },
  "asChild": {
      schema: z.boolean().optional(),
      design: "plumbing",
      description: "usually wraps a Button or icon",
  },
  "side": {
      schema: z.enum(["top", "right", "bottom", "left", "start", "center", "end"]).optional(),
      design: "knob",
      default: "top",
  },
  },
});
