// The "@brightlocal/data" module: named datasets, one per JSON file in
// ./data. In Studio this is generated by generate-registry-lib.mjs; here
// it is a plain module so a new dataset is one import line.
import minusOneStudios from "./data/minus-one-studios.json";
import harbourCo from "./data/harbour-co.json";
import northsideDental from "./data/northside-dental.json";

export const DATASETS = {
  "minus-one-studios": minusOneStudios,
  "harbour-co": harbourCo,
  "northside-dental": northsideDental,
};
