"use client";

// Promoted from Studio screen "RM — Reviews Hub — Trends B (arrow only)"
// (design dmtr3ukx8k2ox, version 1788892766000). Registry: lib/screens.ts;
// re-promotion workflow: apps/brightlocal/README.md.
// source-hash: 0486db65199d

// Reviews — top-level landing (nav model v2). Generated from
// templates/hub-blank.jsx; the shell/sidenav/header live in
// "@brightlocal/proposal" and top-level nav wiring comes from the
// module's DEFAULT navLinks.

import {
  SidebarProvider,
  SidebarTrigger,
  GlobalLayoutContentBody,
  Logo,
} from "@brightlocal/ui-components";
import {
  Card,
  CardHeader,
  CardContent,
  CardFooter,
  CardDescription,
} from "@brightlocal/ui-components/card";
import { Button } from "@brightlocal/ui-components/button";
import { Menu, ArrowRight } from "@brightlocal/icons";
import {
  AppLayoutShell,
  ProposalSidebar,
  PageHeader,
  CardTitleLink,
} from "@brightlocal/proposal";

/* ================================ reference =============================== */

// THE CARDS CARRY NUMBERS NOW (Ali, 3 Sep: "bring some kind of information
// onto the cards, 3 items maximum, maybe one key number and a breakdown").
//
// They were deliberately bare, and the reason still stands: a made-up count
// on a landing page is the kind of thing that gets quoted back as fact. So
// none of these are made up. EVERY FIGURE BELOW WAS READ OFF THE PAGE THE
// CARD LINKS TO, on 3 Sep, from its live render:
//
//   Review Manager      the status tab counts — 60 all, 26 needs action,
//                     7 manually replied, 22 auto-replied, 5 skipped
//   Review Tracker   the Sources card — 1,116 reviews, average 4.7 — and
//                     the ratings breakdown, 836 five-star of 1,116
//   Review Builder       the campaign cards — 5 campaigns, 3 live, 1 draft,
//                     1 stopped
//   Review Showcase    the two seeded widgets — one live feed, one hand-picked
//
// Ali, 3 Sep: "use it from the seed if we can, don't have to necessarily
// update". So these are STATIC, and that is a deliberate trade rather than
// an oversight: there is no store shared across RM's screens, so the only
// alternative is four numbers that silently disagree with the pages they
// summarise. If a seed changes, change it here too — that is what this
// comment is for.
//
// ONE HEADLINE, THEN A BREAKDOWN, capped at three parts. A hub card is read
// in about a second on the way somewhere else: the headline is the number
// that decides whether you go, and the breakdown is only there to stop the
// headline being ambiguous. Four parts turns a signpost into a report.
// ── TRENDS: READ THIS BEFORE QUOTING ANY OF THEM ─────────────────────
// Ali, 7 Sep: "we might want to show Trends for each section. Is there
// anything visual we can get in there?" This screen is the copy where that
// is being tried, so the sparklines are here to be judged as a DESIGN, and
// exactly one of the four is currently wired to real data:
//
//   Review Tracker   REAL. Generated by the same mulberry32(20260816) seed
//                    and daysAgo = 1095 * rand()^1.3 distribution the Review
//                    Tracker page itself uses, bucketed into twelve months:
//                    [31,22,34,34,26,31,40,43,41,33,48,80], 463 reviews in
//                    the last twelve months. Re-derive it, do not hand-edit.
//
//   Manager / Builder / Showcase   SHAPED, NOT MEASURED. Their pages hold no
//                    twelve-month series to read: the Manager seeds 60
//                    reviews over about 90 days, the Builder stores per
//                    campaign totals with no monthly split, and the Showcase
//                    has no time data at all. These three exist so the grid
//                    can be judged as a layout. They must be wired or pulled
//                    before this screen is shown to anyone who might quote
//                    them, which is the same rule the counts below already
//                    follow.
//
// The percentage is last period against the one before it, not first-to-last
// across the whole line, because that is what "up 12% this month" means to
// the person reading it.

const HUB_CARDS = [
  {
    title: "Review Manager",
    // SHAPED SERIES, REAL SENTIMENT RULE. goodWhen "down": a queue of
    // unanswered reviews growing is bad news, so this renders RED even though
    // the arrow points up. Needs the Manager's 60 seeded dates bucketed weekly.
    trend: { series: [18, 21, 19, 24, 22, 27, 25, 31, 28, 26, 24, 26], value: 8, format: "percent", goodWhen: "down", period: "vs last month" },
    lede: "Manage every review for this location",
    goto: "screen:dmsxf5zjggd0n",
    hook: "reviews-hub-inbox",
    // The headline is the one that implies an ACTION. "60 reviews" is a
    // fact; "26 need a reply" is a reason to click.
    headline: "26",
    headlineLabel: "need a reply",
    parts: [
      { k: "Replied", v: "29" },
      { k: "Skipped", v: "5" },
      // ASSUMPTION, needs Ali's call (6 Sep). This says 60 all time while the
      // Review Tracker card beside it says 1,116 reviews for the same
      // location. Both are honest to their own page: the Manager seeds 60
      // rows and its period filter genuinely offers "All time", the Tracker
      // aggregates 1,116. Sitting side by side on the hub, they read as a
      // contradiction. Cheapest fix is relabelling this part "In your inbox";
      // the real fix is reconciling the two seeds. Left as-is pending a call.
      { k: "All time", v: "60" },
    ],
  },
  {
    title: "Review Tracker",
    // REAL, AND IN THE RIGHT UNIT. Average rating of the reviews RECEIVED in
    // each of the last twelve months, from the Tracker's own generator:
    // 4.88 last month, 4.76 this month, so -0.12 of a star. Note it is the
    // per-month rating, not the all-time average: that one only moves from
    // 4.65 to 4.68 across the whole year, because a cumulative mean cannot
    // move once it has a thousand reviews under it. A flat line is honest and
    // useless, which is the argument for plotting the period, not the total.
    trend: { series: [4.63, 4.57, 4.74, 4.24, 4.86, 4.95, 4.85, 4.7, 4.51, 4.57, 4.88, 4.76], value: -0.12, format: "rating", goodWhen: "up", period: "vs last month" },
    // NOT "charts and tables" (Ali, 3 Sep: "that summary is not so
    // insightful"). It described the FURNITURE — what the page is made of,
    // not what it is for. Every other card here says what you would learn or
    // do; this one said what widgets are on the page.
    //
    // Two questions, not three (Ali, 3 Sep: "and what is pulling it up or
    // down — not needed, it is fluff"). It was, and it was the tell: the
    // clause named no object, so it could have been appended to any of the
    // four cards without changing meaning. Where reviews come from and how
    // the rating moves are the two things the page actually answers.
    lede: "Location sources and ratings over time",
    goto: "screen:dmswb0i9c6oe5",
    hook: "reviews-hub-insights",
    headline: "4.7",
    headlineLabel: "average rating",
    parts: [
      { k: "Reviews", v: "1,116" },
      { k: "Five star", v: "836" },
      // SEVEN, matching the page (6 Sep). Four was the number of NAMED donut
      // slices; the page now counts every source with reviews, including the
      // three folded into Other.
      { k: "Sources", v: "7" },
    ],
  },
  {
    title: "Review Builder",
    // SHAPED. Needs reviews-gained split by month across the nine campaigns.
    trend: { series: [4, 7, 6, 11, 9, 14, 12, 18, 16, 21, 19, 24], value: 26, format: "percent", goodWhen: "up", period: "vs last month" },
    lede: "Invite your visitors to leave a review",
    goto: "screen:dmt094j963aye",
    hook: "reviews-hub-get",
    // COUNTED OFF THE PAGE, not remembered (6 Sep). The table shows nine
    // campaigns: 4 Live + 1 Sending are the five actually running, then one
    // Scheduled, one Draft, one Finished and one Stopped. The hub said 3 of
    // 5, which was true of the card grid this table replaced.
    headline: "5",
    headlineLabel: "campaigns running",
    parts: [
      { k: "Scheduled", v: "1" },
      { k: "Draft", v: "1" },
      { k: "All time", v: "9" },
    ],
  },
  {
    title: "Review Showcase",
    // SHAPED. The Showcase has no time series of any kind behind it yet.
    trend: { series: [2, 2, 3, 3, 4, 5, 5, 6, 8, 7, 9, 11], value: 22, format: "percent", goodWhen: "up", period: "vs last month" },
    lede: "Publish your best reviews on your site",
    goto: "screen:dmt094lhmpwbs",
    hook: "reviews-hub-widgets",
    headline: "2",
    headlineLabel: "widgets published",
    parts: [
      { k: "Live feed", v: "1" },
      { k: "Hand-picked", v: "1" },
    ],
  },
];

// HubCard / DrillArrow are lifted VERBATIM from UI Vision - Location Hub
// (dmrurue2wmp9u), which is where the pattern is set.
function DrillArrow() {
  return (
    <Button
      variant="secondary"
      aria-hidden
      tabIndex={-1}
      dataHook="hub-drill-arrow"
      className="pointer-events-none size-9 shrink-0 rounded-full p-0 group-hover:bg-secondary/80"
    >
      <ArrowRight className="size-4" />
    </Button>
  );
}

/* ================================= trends ================================= */

// PLAIN SVG, NOT RECHARTS. A sparkline is a polyline and a dot; pulling a
// charting library in for 60x20 pixels costs a dependency the hub does not
// otherwise have, and the panel renderer blocks network so every new import
// is a risk. This has no axes, no grid, no tooltip and no legend on purpose:
// at this size the only readable message is the SHAPE, and anything else is
// ink competing with the headline number beside it.
function Sparkline({ series = [], w = 72, h = 24, dataHook }) {
  if (series.length < 2) return null;
  const min = Math.min(...series);
  const max = Math.max(...series);
  const span = max - min || 1;
  // 1px inset top and bottom so the stroke is never clipped at the extremes.
  const pt = (v, i) => [
    (i / (series.length - 1)) * w,
    h - 1 - ((v - min) / span) * (h - 2),
  ];
  const pts = series.map(pt);
  const d = pts.map((q, i) => `${i ? "L" : "M"}${q[0].toFixed(1)},${q[1].toFixed(1)}`).join(" ");
  const last = pts[pts.length - 1];
  return (
    <svg
      width={w}
      height={h}
      viewBox={`0 0 ${w} ${h}`}
      className="overflow-visible"
      data-hook={dataHook}
      aria-hidden="true"
    >
      <path
        d={`${d} L${w},${h} L0,${h} Z`}
        fill="var(--ds-tailwind-colors-green-100)"
        opacity="0.5"
      />
      <path
        d={d}
        fill="none"
        stroke="var(--ds-tailwind-colors-green-600)"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <circle cx={last[0]} cy={last[1]} r="2" fill="var(--ds-tailwind-colors-green-600)" />
    </svg>
  );
}

// ONE SWITCH FOR THE WHOLE GRID (Ali, 7 Sep: "It could also be that we just
// have an up arrow"). Flip to "arrow" to see the four cards with direction
// only and no figure. Kept as a constant rather than a per-card prop because
// a grid where some cards quantify and others do not reads as an oversight.
const TREND_STYLE = "arrow"; // "value" | "arrow"

// A DELTA IS ONLY READABLE IN ITS OWN UNIT (Ali, 7 Sep: "Up 67% for a review
// average doesnt help me"). Quite right, and it was wrong twice: the Tracker
// card's headline is an average RATING, but the trend under it was plotting
// review VOLUME, and then expressing it as a percentage. "Up 67%" of a 4.7
// average is not a quantity that exists. So the unit travels with the number:
//
//   rating   +0.12 / -0.12   points of a five point scale, two decimals
//   percent  +8%             a proportion, where the base is obvious
//   count    +3              whole things, where the base is small
//
// DIRECTION IS NOT SENTIMENT. Up is good for a rating and bad for a queue of
// unanswered reviews, so the arrow says which way it moved and `goodWhen`
// decides whether that is green or red. Colour is not the only carrier: the
// arrow and the figure both still read with colour removed.
function formatDelta(value, format) {
  const n = Math.abs(value);
  if (format === "rating") return n.toFixed(2);
  if (format === "percent") return `${Math.round(n)}%`;
  return String(Math.round(n));
}

function TrendChip({ trend, hook }) {
  if (!trend) return null;
  const up = trend.value >= 0;
  const good = (trend.goodWhen ?? "up") === (up ? "up" : "down");
  return (
    <span
      className="text-muted-foreground flex items-baseline gap-1 text-xs"
      data-hook={`${hook}-trend`}
    >
      <span className={good ? "text-success font-medium" : "text-destructive font-medium"}>
        {up ? "\u2191" : "\u2193"}
        {TREND_STYLE === "value" ? ` ${formatDelta(trend.value, trend.format)}` : ""}
      </span>
      <span>{trend.period}</span>
    </span>
  );
}

function HubCard({ card }) {
  return (
    <Card
      className="group h-full max-w-none cursor-pointer gap-4 transition-shadow hover:shadow-sm"
      dataHook={card.hook}
      data-grade-goto={card.goto}
    >
      <CardHeader>
        <div className="flex items-start justify-between gap-3">
          <div className="flex min-w-0 flex-col gap-1.5">
            <CardTitleLink>{card.title}</CardTitleLink>
            <CardDescription>{card.lede}</CardDescription>
          </div>
          <DrillArrow />
        </div>
      </CardHeader>
      {/* mt-auto ON THE CONTENT, BREAKDOWN IN THE FOOTER (Ali, 3 Sep: "put
          the summary numbers in the footer, so they stick to the bottom").
          The four ledes are different lengths — Review Tracker wraps to two
          lines, Review Manager does not — so without this the numbers sat at
          four different heights across a 2x2 grid and the eye had nothing to
          run along. Pushing the content down pins the headline AND the
          breakdown to the bottom edge, so the numbers line up across the row
          whatever the copy above them does. */}
      <CardContent className="mt-auto flex flex-col gap-3">
        {/* THE HEADLINE READS AS A SENTENCE, not as a stat tile. A tile
            would put this card in competition with the module cards on the
            location hub, which ARE stat tiles; this is a signpost with a
            number on it. Number and label share a baseline so they read as
            one phrase rather than as a label above a value. */}
        {/* The sparkline sits to the RIGHT of the headline, on the same row.
            The headline row was half empty, and a trend belongs next to the
            number it qualifies rather than under it: putting it below would
            push the footer breakdown down and undo the alignment the whole
            mt-auto arrangement above exists to protect. */}
        <div className="flex items-end justify-between gap-3">
          <p className="flex items-baseline gap-2" data-hook={`${card.hook}-headline`}>
            <span className="text-3xl font-bold tracking-tight tabular-nums">{card.headline}</span>
            <span className="text-muted-foreground text-sm">{card.headlineLabel}</span>
          </p>
          {card.trend ? (
            <div className="flex shrink-0 flex-col items-end gap-1">
              <Sparkline series={card.trend.series} dataHook={`${card.hook}-spark`} />
              <TrendChip trend={card.trend} hook={card.hook} />
            </div>
          ) : null}
        </div>
      </CardContent>
      {/* The breakdown is one row, not a stack: three short key/value pairs
          fit across a half-width card, and stacking them would make the card
          twice as tall for the same three facts. */}
      <CardFooter className="border-t pt-3">
        <dl
          className="text-muted-foreground flex flex-wrap gap-x-5 gap-y-1 text-sm"
          data-hook={`${card.hook}-parts`}
        >
          {card.parts.map((p) => (
            <div key={p.k} className="flex items-baseline gap-1.5">
              <dt>{p.k}</dt>
              <dd className="text-foreground font-medium tabular-nums">{p.v}</dd>
            </div>
          ))}
        </dl>
      </CardFooter>
    </Card>
  );
}

export default function RMReviewsHubTrendsBArrowOnlyPage() {
  return (
    <SidebarProvider dataHook="provider" defaultOpen>
      <AppLayoutShell
        preset="live-site"
        navDensity="comfortable"
        stickyHeader
        flush
        pinnedSidebar
        dataHook="reviews-app-layout"
        sidebar={<ProposalSidebar dataHook="reviews-sidebar" activeId="reviews" />}
        mobileBar={
          <div className="flex items-center gap-3 border-b px-4 py-3 lg:hidden">
            <SidebarTrigger dataHook="mobile-trigger">
              <Menu className="size-5" />
            </SidebarTrigger>
            <Logo className="h-5" dataHook="mobile-logo" />
          </div>
        }
        header={
          <PageHeader
            dataHook="reviews-page-header"
            breadcrumbs={[
              { label: "All Locations", goto: "screen:dmrotrgstba3l" },
              { bind: "location", goto: "screen:dmrurue2wmp9u" },
            ]}
            title="Reviews"
            // IT WAS LISTING THE CARDS (Ali, 7 Sep: "this is also truly
            // awful"). Four clauses, one per card, sitting directly above four
            // cards that each carry a title AND a lede: the page said
            // everything twice and the description was the weaker telling.
            // A page description should say what the PAGE is, and leave the
            // cards to say what they are. Deleting it outright breaks the
            // standing rule that every proposal page carries one (20 Jul), so
            // this is the shortest line that does the job.
            description="Everything you need to increase your reputation"
          />
        }
      >
        <GlobalLayoutContentBody dataHook="reviews-page-body" className="space-y-6 pb-10">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            {HUB_CARDS.map((card) => (
              <HubCard key={card.hook} card={card} />
            ))}
          </div>
        </GlobalLayoutContentBody>
      </AppLayoutShell>
    </SidebarProvider>
  );
}
